### ISSUE TITLE
Email server needed

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#1]
Divio does not provide email services, but it isn't too hard to hook what we have up to an SMTP server from another source.  Need to get server info figured out w. @burlexpo

**Comment by burlexpo** [comment]
Just let me know what info you need.  I can also do something like set up mail.burlesque-expo.com if that's easier...

**Comment by bethlakshmi** [comment]
Done.  Code to make the 3 configurations safe and the username/passwords for in motion are all set and tested and working.
