### ISSUE TITLE
Make volunteering as easy as being interested

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#101]
We let people be interested in an event almost anywhere:
- on the list of events
- on the calendar
- on the event description

And it always works the same - there's an icon (always the same) that toggles participation on and off.

We want volunteering to work the same way.

**Comment by bethlakshmi** [comment]
Yep, pattern is pretty easy to replicate:

https://burlesque-expo-stage.us.aldryn.io/scheduling/view_list/Volunteer/

Is the first round - putting it on the list of Volunteer Events in the same place as the "interested" star.

I'm a little worried that the boxes aren't all that intuitive... but I don't have a better idea.

**Comment by burlexpo** [comment]
> I'm a little worried that the boxes aren't all that intuitive... but I don't have a better idea.

I'm not sure how confusing they arem but we could use stars (in differing colors) like we do for expressing interest in other things...

**Comment by bethlakshmi** [comment]
I'd like to keep stars for interest.
Maybe this is good enough.
Detail view is done now - on to testing

**Comment by bethlakshmi** [comment]
OK @burlexpo  - one more question....

In the new icons, if you are previously rejected for volunteering for this, I disable the icon and link.  And I give a message, based on role.  This is great for stuff like teachers/performers... but it seems too blunt:

![Screen Shot 2020-03-12 at 8 33 20 AM](https://user-images.githubusercontent.com/4542707/76522117-685d9400-643c-11ea-8ee0-c822342ec868.png)

Should I map this to something a bit nicer?  Maybe "we don't need your help, thanks"?

**Comment by burlexpo** [comment]
I think just turn it around.  "Thank you for volunteering.  You were not accepted for this shift".

**Comment by bethlakshmi** [comment]
deployed!
