### ISSUE TITLE
Act Tech Info Reports

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#102]
OK, just approved PR for #94 

For the tech crew, I think we need:

**Show Summary page**

a report summary for everyone (Mike, Hunter, Stage Managers but really it's not secret) - that has:
    - is the act complete? (highlighted in red)
    - when is the act rehearsing? 
    - order in show
    - Performer name, act name
    - link to the track for the song
    - link to all the details 
    - link to video from bid - IFF the video is of the actual act.  If it was "another act, not what I'm performing" or no video - say "video of act was not submitted".

- on this screen - stage managers & producers should be able to delete acts from the show (which also removes rehearsal booking) -- this would eliminate the need for giving them access to the review stuff.

... anything else for the summary?  Most of this is done, just need the delete button and the link to details.

Act Details

Link on Summary page shows these act by act.  But there is also a "get all details" link on the summary page that gives every single act, sorted by show order.

This would be a page with the following details:

Act Summary (top of page):

BIGGEST/HEADER = Show, Order, Performer Name
- picture of performer (from profile)
- title of act
- description of act (from bid),
- feel of act (from tech info)
-  colors of costume,
- duration of act
- pronouns
- starting position - I'm putting at the top because EVERYONE uses this - audio, lighting, stage kittens, etc.

MC Info:
- introduction
- read exactly?

Stage info:
- prop & stage kitten instructions

Audio Info:
- name of track, Title, Artist - or confirm no music
- mic options

Lighting Info:
- follow spot yes/no - follow spot color (optional)
- cyc color (optional)
- wash color (optional)
- start in blackout
- end in blackout

The print-friendly version should also have a created-on date to show when the form was printed.  This should be on every page -- the tech crew will likely print multiple copies if things are chaotic, and they will want to know which is the most recent.

**Comment by bethlakshmi** [comment]
First try is ready:

https://burlesque-expo-stage.us.aldryn.io/reports/acttechinfo/view_summary/971

- The navigation is slightly different - there's an entry in Reports part of the Special menu.

- Then the summary (what you see here) - is quite similar.... the big difference is the 3 buttons.

- Then the BIG difference is the view - good example is Betty's act for the Main Event - I gave myself all the bells and whistles:  https://burlesque-expo-stage.us.aldryn.io/reports/acttechinfo/detail/1295

I still need to:
- massage some navigation stuff
- implement delete
- play with screen size and make sure layout stays nice (currently tested on a desktop)

But this is a good time to get feedback.

**Comment by burlexpo** [comment]
• _Preferred Pronouns_ should be part of MC info
• I feel like _Starting Position_ is kind of hanging out by itself. If we can put it in two places, it should be in both Lighting and Sound (the line above **Starting Lights** and the line above **Mic Options**.  If we can't put it there,  it probably wants to be where _Preferred Pronouns_ are now.
• The labels for Costume colors are ambiguous and should be under  **Lighting**.  If possible, I would do something like:
     **Costume Colors**
          _Primary:
         Secondary:_
If you can't add that header (Costume Colors) can we change the label to "Primary Costumer Color" and "Secondary Costume Color"?

**Comment by bethlakshmi** [comment]
How's this?
https://burlesque-expo-stage.us.aldryn.io/reports/acttechinfo/detail/1295

Did I cover everything?

**Comment by burlexpo** [comment]
That was everything.  Looks good!

**Comment by bethlakshmi** [comment]
found deploy problem installed code
