### ISSUE TITLE
Move all the dates to Labor day weekend for GBE 2020

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#103]
Move every booked event for GBE 2020 from April 17-19 to Sept. 4-6.
That's mostly the scheduler.Events data.
Might as well also move Conference Days.

**Comment by burlexpo** [comment]
I've reset the conference days already.

**Comment by burlexpo** [comment]
Also changed the header and footer on the site and the front page of the site.
