### ISSUE TITLE
Conference Cal defaults to 2018

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#106]
When I click _The Conference > Saturday Class Schedule_ I get shown the classes for Saturday, Jan. 6, 2018 (Expo12) instead of Saturday, Sept. 5, 2020 (Expo13).  I can click the adjustment buttons above to get where I want, but relying on users to do that seems like a Bad Thing.

**Comment by bethlakshmi** [comment]
The links you are referring to are NOT user visible. 
The custom code of GBE also doesn't control them.  These are made in Django CMS and you or I hid them when we started ramping up GBE 2020.

You can see this on the Django pages list in the admin:

![Screen Shot 2020-03-14 at 12 49 31 PM](https://user-images.githubusercontent.com/4542707/76686537-6f2e0780-65f2-11ea-895d-ac2d5a804e6f.png)

The blue dot is "unpublished changes"

Also - the way these links work, is that a date is hard coded into the page link for what day to show.  The day we asked it to show is:

Saturday = 1-06-2018
Sunday = 1-07-2018

![Screen Shot 2020-03-14 at 12 52 52 PM](https://user-images.githubusercontent.com/4542707/76686586-e6639b80-65f2-11ea-98c3-83aec701aa73.png)

This is off the same page admin menu, it's the Advanced Settings.

**Comment by bethlakshmi** [comment]
I did the following:
- changed links in Django CMS for both shows and conference day calendars to be our new days.
- make Sat & Sun display publicly.
- disabled Friday and "... sit on a Panel" as we don't have a reason to use those right now

I'm trying to test, but I believe that the caching is slowing down my testing.   I'm testing both as myself, and as a not-logged-in user.   Neither one is right yet, although the links for shows are now OK.

Will test more later.

But @burlexpo  - log out and test yourself, too, please.  I see that the Opening Number page has an unpublished version and I'm not sure what else might be not-as-you-expect.
