### ISSUE TITLE
Time to map rooms to conferences

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#11]
Salem will be a whole new space.  We should hide the Hyatt Regency rooms and create new rooms for our new site.
@burlexpo  - I'm also thinking we may want to add a more descriptive stuff, to rooms - for example building & address... given that we may have multiple locations.

--------
Notes on Implementation:

- New rooms can be be made in the /admin area in the item "Rooms".  They are now filterable by conference and when you create/edit a room you get to set the original stuff (name, capacity, overbook size) and also "address" and "map link" - I've been deliberately brand-free on what kind of map - a link to any map should work (in case something doesn't work right in Apple or Google).  Address is ~500 characters.  Also you MUST set a conference link.  It's a multi-select - so a room can be used in multiple conferences.

- event detail displays (not summaries/lists) - show the event, address and map link if all are provided.  If there is no data provided, it doesn't look any different.

- when creating/editing an event, the list of rooms is only those rooms available for the conference of this event.  ie, an event for GBE 2020 can only get rooms that are affiliated with GBE 2020.

- when copying an event, things get REALLY fun...
    - in a copy of a single event (like a drop in class), the user can now choose room as well as day.  If the room from the original event is available for this conference, then that room is set as the default choice.  If not - the user will have to select something else (it's required).
    - in a copy of a staff area or an event with sub-events (like a Show) - there is a "default room" - the default room also uses the staff area default room or the parent event room as it's default choice.  The big difference here is that the "default room" is only used when an event/staff area *can't* have the room it originally had because the original room is not a part of this conference.  The point being that the copy function tries to preserve as much of the original settings as possible.  That doesn't matter much this year (nothing is in the same place), but it would help if we go back to Salem but don't keep ALL of our rooms...

There are some less visible improvements - the reporting tools filter by room, to limit a pile of data... I found some display bugs here and there and may have fixed them.  

Other stuff like daily schedules or the schedule on the user's home page, doesn't change, although they all link to the event details... which DID change.

**Comment by bethlakshmi** [comment]
Moved code onto test server and put in two rooms for Salem, and set up all our old rooms with their conferences.

**Comment by bethlakshmi** [comment]
Found a bug.  I created two rooms called "Theater" - one to represent the years at the Hyatt.  And one for the new location.  It causes a bug when setting a Volunteer event!  Will fix before pushing to test.  In the meantime, I set the value to be different so @burlexpo won't encounter the same bug when playing

**Comment by burlexpo** [comment]
Since we are now going to have multiple addresses associated with a single conference (i.e., the main event is at one address, the conference is at a different address, a reception might be able to third address), can we have an option to display the location name and/or the street address associated with an event?

--
Team BurlExpo
www.Burlesque-Expo.com
#BurlExpo

**Comment by bethlakshmi** [comment]
@burlexpo - that's what I did already - here's a demo:

https://burlesque-expo-stage.us.aldryn.io/scheduling/details/970

I don't know why there is a weird ass a> being displayed.  I suspect I have to fix something.

But is that about what you had in mind?

**Comment by burlexpo** [comment]
That's about what I had in mind.  Any reason why we don't do a thumbnail map as the link? Something like this:

<img width="1440" alt="Screen Shot 2019-11-30 at 5 09 05 PM" src="https://user-images.githubusercontent.com/5369404/69906626-65aac780-1394-11ea-843e-0ef2040c5ca3.png">

**Comment by bethlakshmi** [comment]
No particular reason...  I can do that, I'll do before I publish changes.
The process to set it up is to go to the Admin (/admin or "Administration..." in the top header):
- Pick Rooms
- edit or create a room and there is a space for address and for "map link" - which would take any link.  I think I tried Apple and Google Maps.

I'll change the map link to an embed tag and display it the way you show.

**Comment by bethlakshmi** [comment]
FYI - I'm going to mess up the test database for a bit.  I'm pulling Live to Test and then updating for a map embed tag.

**Comment by bethlakshmi** [comment]
OK, database updated... 
https://burlesque-expo-stage.us.aldryn.io/scheduling/details/986

How's that?  if you like it, I'll move it to live ASAP.

**Comment by bethlakshmi** [comment]
Pushing to Live.  - It will preserve your rooms, and I will make sure the rooms are set to conferences, but I'll need you to set up addresses if you give me a link to a google map, I can set up the embedded map.

**Comment by burlexpo** [comment]
OK.  Is this something I can edit after the fact through Admin? I figure that under "Rooms" there would be a place to enter the street address and a URL for an embed map.

**Comment by bethlakshmi** [comment]
Yes - exactly - /admin and then the secton "Rooms".  For embedding the map, it's not a URL, it's a hunk of code.  It's in one of the Google icons and then the choice is "Embed" and gives a hunk of code.  I recommend smallest of the smalls - it's what I designed the layout for.

But if you can put in the address, I can generate the embedded tag.

The update is live.  And rooms are attached to conferences.  I'm going and testing updates, but if you don't hear from me, it's all good.

**Comment by bethlakshmi** [comment]
Pushed to live.  Looking good.
