### ISSUE TITLE
"Email Everyone" doesn't work

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#112]
I just tried using the Email Everyone button on http://burlesque-expo.com/email/mail_to_bidders  Got my list of 732 people, but when I clicked "Send" I got 

Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

I'm trying to send out info about the BurlExpo Zoom meeting on 4/18 so this is kind of sensitive

**Comment by bethlakshmi** [comment]
Got my shit together - it's definitely reproducible in my test environment.

Very strange.  Workin on it.
