### ISSUE TITLE
export calendar is sooooooo slooooowww...

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#115]
Shall I try to fix it?  Or remove it?  Are we still exporting?  We used to do this for that mobile app client tool but now we should be mobile ready on the site....  

It's messy so I'd be happy to avoid fixing it.

**Comment by burlexpo** [comment]
What exactly does it export? I think that people like Mr. Bergman like to have printed reports of their volunteers by shift, but I also think we have other options for that now.  I think we can delete this.

**Comment by bethlakshmi** [comment]
It doesn't do that.  It's title, description, start/end time, room. 
It's what Mina used to use to import into Guidebook and nothing else.

**Comment by burlexpo** [comment]
Yeah — kill it

--
Team BurlExo
Burlesque-Expo.com
#BurlExpo
