### ISSUE TITLE
Bogus Accounts

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#140]
I was researching a different issue using Manage Users when I noticed a bunch of obviously bogus accounts — many from Russia — that had been created in the last 4-6 weeks.

Here are some examples (user names):

agrohimgkj
Zelenaxrx
Bogdanwpj
Pavlosgee
DavidBeige
Keithhex
AAligueillilla

Weren’t we using CAPTCHA to keep this for happening?

**Comment by bethlakshmi** [comment]
Hmm... so I'm researching:

https://datadome.co/bot-detection/recaptchav2-recaptchav3-efficient-bot-protection/

Makes me wonder if I want to go from what we have (recaptchav2) to recaptchav3.  I could also look at other brands.
Too tired for this right now... but noting it for later.

**Comment by bethlakshmi** [comment]
Closing - I now have a bad people email list that we check.  It caught problem children like these, and so far seems to have been effective since it was installed.
