### ISSUE TITLE
BPT Tickets integration needs some love

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#15]
The speed at which this code was written is starting to show.  It's not easy to debug when you haven't been looking at it, and failures that are encountered are not circulated up to the user as well as they ought to be.

I also think that the number of API calls are not that efficient, so we're calling BPT way more than we need to be.

Items to review and fix:
- **Multiple threads** - error handling around each type of perform_bpt_api_call - the function calling this one should log what it was trying to do, and possibly circulate some failures up to the user.  
- **Ticket Item Import** - I think we can make assumptions about the state of BPT (for example, that a BPT event in our database ought to be in BPT if everything is working right) -- so we have some ability to give better feedback when the user has bad data on our side.  That is definitely a risk during a data migration, but it's also a case of common human error.  This is bulk, so giving some info on what cases failed vs. what succeed is really helpful to the user.

**Comment by burlexpo** [comment]
@bethlakshmi - can this be closed or deleted since it's irrelevant?

**Comment by bethlakshmi** [comment]
Yes.  The Event brite stuff introduced an Admin view to help with exactly this.
