### ISSUE TITLE
small stuff that bugs me

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#167]
Doing the styes work, I'm finding static text and other ugliness that should be fixed.  It's stuff from the early days that I've figured out how to do better.
- ~~ class proposal intro block is hard coded in the template~~ - POST PONE, probly remove intro block.
- ~~long list of model choices in review forms should only show the selected option - example - costume review shows every performer in the system, with the actual choice in bold.  I think we may have it with US states, too.~~
- the password reset & user registration is rife with static text.  Also, WTF are those breadcrumbs?  Are they used anywhere???? - DELAYED, based on conversation below, I don't care enough to start a new ticket right now.
- I want to make a password change for the user to do themselves.  This is native django functionality that we never tapped into.  It doesn't come up alot, but why have this be something we have to do? - DELAYED, based on conversation below, I don't care enough to start a new ticket right now.
- event wizards also have a ton of static text - pull that into user messages
- ~~if you put in a negative number for max_volunteer when you input a new volunteer event - you get an uncaught exception, hence an ugly error outside of debug.  Catch it and error property and put in a min value for the field, so the user will have to try harder to hit this.~~
- ~~static text on edit email template page~~
- ~~left hand panel on user home page used to be a Django CMS element that we could edit.  With the port, this has always been broken.  Replace with a text block that can be edited by the Admin with the rich text editor, and is stored as a UserMessage in our DB~~
- ~~sidebar-text - historical and normal - is hard coded on the template~~
- copy wizard (events and staff area) - is full of all sorts of text - it's isolated in form text, but I don't think it's ediable.  Check on that.

**Comment by bethlakshmi** [comment]
- [ ] class proposal intro block is hard coded in the template
- [ ] long list of model choices in review forms should only show the selected option - example - costume review shows every performer in the system, with the actual choice in bold. I think we may have it with US states, too.
the password reset & user registration is rife with static text. Also, WTF are those breadcrumbs? Are they used anywhere????
- [ ] I want to make a password change for the user to do themselves. This is native django functionality that we never tapped into. It doesn't come up alot, but why have this be something we have to do?
- [ ] event wizards also have a ton of static text - pull that into user messages
- [ ] if you put in a negative number for max_volunteer when you input a new volunteer event - you get an uncaught exception, hence an ugly error outside of debug. Catch it and error property and put in a min value for the field, so the user will have to try harder to hit this.
- [ ] static text on edit email template page
- [ ] left hand panel on user home page used to be a Django CMS element that we could edit. With the port, this has always been broken. Replace with a text block that can be edited by the Admin with the rich text editor, and is stored as a UserMessage in our DB
- [ ] sidebar-text - historical and normal - is hard coded on the template
copy wizard (events and staff area) - is full of all sorts of text - it's isolated in form text, but I don't think it's ediable. Check on that.

**Comment by burlexpo** [comment]
_I want to make a password change for the user to do themselves. This is native django functionality that we never tapped into. It doesn't come up alot, but why have this be something we have to do?_

Isn't the password change function the same as the password recover function? What we don't have is a way for the user to do it on-site (I.e., enter the old password in a field, enter the new password twice to confirm it, click 'change') but we do have something that emails a change link to the user -- don't we?

**Comment by bethlakshmi** [comment]
Correct.  So - you can go through the rigamarole of sending yourself an email, digging it out, and resetting that way.  But not something that is relatively standard on every other site - going on the site, changing your password, and being done with it.

Note - that's 1 of 10 dumb little bits of tech debt that will take me 20 minutes or less.

If you want me to move on to big things, it would help to know if Paypal is usfeul for you or if you are wiling to pay fees for me to integrate with Simple Tix on #206 - today I'm fried and not starting on researching paypal - but my expectation is that the two are close enough, that it won't matter.... so it helps to know what's useful to you - paypal for free, or simple tix for $.

**Comment by burlexpo** [comment]
@bethlakshmi Yes, we should move to SimpleTix/Zapier.

**Comment by bethlakshmi** [comment]
Merged the low hanging fruit.  I'll review the rest and see whether to close or create a new ticket for the harder stuff on the list

**Comment by bethlakshmi** [comment]
On review, I'm just gonna close this and not make more - the rest of this is so low priority.
