### ISSUE TITLE
Make an "unsubscribe" option and put as footer in all Emails

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#17]
This is really two parts:

1 - add email unsubscribe capability to a User's Profile (or as a separate page in the same area).  My recommendation is to give them separate options:
- un/subscribe from bid notifications (all bid types, 1 switch)
- un/subscribe from role notifications (all roles types, 1 switch)
- un/subscribe from schedule change notifications (ie, getting signed up/unsigning up for volunteer slots)
- un/subscribe from daily schedule email (sent nightly the day before for any day that the user has a scheduled commitment)

Those are the 4 threads that make the most sense for a user to opt out of.  They do NOT include direct emails for established relationships, and the do not include account maintenance emails - like password recovery processes.  The work to be specific about what type of communication the user is disabling gives a lot of value - the user gets a better feature and we get users specifically opting in/out of what they really want.  And it's not a heck of a lot more work for development (or... I'll let you know if it is) and gives better future extensibility.

My hope is that the user would not, once they see the list, forbid all types of contact.  We rely on being able to email people about what they have committed to.

"Un/subscribe" meaning it's an on/off checkbox.  It defaults ON for all users, and they can turn it off as they like.  I'll think up something sensible (and low effort) to do if the user is marked "invisible" - effectively, if they are invisible, they should not be getting ANY email from us, as the account is disabled entirely and that should supercede ALL email functionality (even password reset).  I reserve the right to do that however it looks easiest to me.  I think from a disabled-account perspective, the work may already be done from the original design.

2 - stick a blanket message for unsubscribing at the footer of EVERY email that would be subject to this feature (ie, the four options listed above).  I'll do it in such a way that anyone editing templated messages can't accidentally remove it (ie, it's outside of any templates).

**Comment by bethlakshmi** [comment]
OK, I will need word help.  Not needed right this minute, but this has the feel of something that wants help:

 code label | what Betty thinks it does | label next to check box | "?" more info
----------- | ------------------------- | ----------------------- | -------------
send daily schedule | We send a schedule the night before any events on the user's schedule.  This would turn it off. | Email my next day schedule every evening | The evening before any day on which you are participating in a part of the Expo, you'll receive an email with your daily schedule from our site.  Turning off this item will disable that feature.
send bid notifications | Removes the user from any time a privileged person uses the contact users by bid email feature.  All bid types, all conferences (including the active one) | Send me offers and updates based on my proposals to GBE | From time to time, the staff of GBE sends emails to the people who have offered to participate in the current or previous Expos.  Turning off this item will disable all communication of that sort, although coordinators of areas in which you have committed to participate in this year's events may still contact you individually.
send role notifications | Removes the user from any time a privileged person uses the contact users by role email feature.  All roles, all conferences (including the active one) | Send me offers and updates based on roles I've had at GBE | From time to time, the staff of GBE send emails to people who have or will in the future acted as volunteers, performers, teachers, vendors, etc.  Turning off this item will disable all communication of that sort, although coordinators of areas in which you have committed to participate in this year's events may still contact you individually.
send schedule change notifications | Removes the user from any time a privileged person uses the contact users by bid email feature.  All bid types, all conferences (including the active one) | Email me when my schedule at GBE changes | The GBE system will automatically email you when a part of the expo you are interested or participating in has changed.  Turning off this item will automatically disable that automated notification.

**Comment by burlexpo** [comment]
**Internal Label:** Send Daily Schedule
**Public sees:** Send me my schedule
**Help Text:** We'll mail you your schedule for the next day (on Friday, you get Saturday's schedule).  This includes any classes you are teaching or have expressed interest in, any volunteer shifts, any scheduled rehearsals, etc.  Opting out will disable this feature.

**Internal Label:** Send bid notifications
**Public sees:** Email me based on my past and current proposals
**Help Text:** If you have applied to teach, volunteer, or perform in the past, we may reach out to you to see if you want do one or more of those things again.  Opting out will keep you from receiving those emails, but will **not** prevent you from getting individual emails about your current commitments.

**Internal Label:** Send role notifications
**Public sees:** Email me based on my past and current activities
**Help Text:** If you have taught, volunteered, performed, sold stuff, or displayed stuff in the past, we may reach out to you to see if you want do one or more of those things again.  Opting out will keep you from receiving those emails, but will **not** prevent you from potentially getting individual emails about your current commitments.

Schedule change notifications is fine as is.

**Comment by bethlakshmi** [comment]
OK - @burlexpo - this is up on the test server: https://burlesque-expo-stage.us.aldryn.io

You should see:
- Your account -> Profile - has 4 new options for the 4 things you can unsubscribe from
- The Contact features now omit users if they turned off the send to bids or send to roles email "subscription" in their profile
- The templates (Manage -> Email Templates) - will always have unsubscribe links in them for the daily schedule, and the volunteer schedule updates.  If the user tries to remove it, it'll just keep coming back.
- The mail to bidders & roles auto-appends the link to whatever you send.
- The email link in the emails directs the user to the update profile page and turns off exactly what email subscription for the email they got.  And highlights it, so they know this is off.  Here's a demo of that:

https://burlesque-expo-stage.us.aldryn.io/update_profile?email_disable=send_role_notifications

NOTE: With the test server - I made it so you CAN'T email to users.  But you basically either email yourself, or me - I forget which.  So if you do any emailing, go into the /admin to see what the email content looks like.

I'll give it a few days, check over my code as a last control, play w. it a little on the test server, and then push to live.

... FYI - I don't see the formatting things you mentioned.

**Comment by bethlakshmi** [comment]
Done!
