### ISSUE TITLE
Migrate all pages

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#18]
Here's my checklist...

From the webfactional site:

 
- [x] About Us
  - [x] Main
  - [x] Q & A with Red Velvet
  - [x] Guests 2016
  - [x] Roll of Winners
  - [x] Location & Directions
  - [x] Staff
  - [x] Get In Touch
- [x] Shows & Events
  - [x] Shows
    - [x] The Rhinestone Revue - REDIRECT
    - [x] The Bordello - REDIRECT
    - [x] The Main Event - REDIRECT
    - [x] The Sunday Showcase - REDIRECT
    - [x] Show Summary - REDIRECT
  - [x] The Exhibit Hall
    - [x] Displays & Events
    - [x] Vendors
    - [x] The Athenaeum
    - [x] Inside the Combat Zone
  - [x] Special Events & Parties
    - [x] Saturday Calendar - REDIRECT
    - [x] Sunday Calendar - REDIRECT
    - [x] Special Event Descriptions - REDIRECT
- [x] I Want To...
  - [x] ...Buy a Ticket - REDIRECT
  - [x] ...Volunteer!
  - [x] ...Submit an Act - REDIRECT
  - [x] ...Submit A Class - REDIRECT
  - [x] ...Submit an Idea - REDIRECT
  - [x] ...Sit on a Panel - REDIRECT
  - [x] ...Sell My Stuff - REDIRECT
  - [x] Vendor FAQ
  - [x] ...Display a Costume - REDIRECT
  - [x] ...Book a Room
  - [x] Video
- [x] Message Received
- [x] Performer Release
- [x] The Conference
  - [x] Friday Class Schedule - REDIRECT
  - [x] Saturday Class Schedule - REDIRECT
  - [x] Sunday Class Schedule - REDIRECT
  - [x] Class Descriptions - REDIRECT
  - [x] Teacher Bios - REDIRECT
- [ ] Secret Full of Bug Page
  
check = FINISHED.
Any page that has children is done when the sub pages are done.
All pages have now been created on https://burlesque-expo.us.aldryn.io/main/ but anything unchecked is either blank or not a good fidelity translation of the original page.

@burlexpo  - the stuff that is marked redirect doesn't need all that much proof reading - it's all deriving from data/code that I wrote.  However, the redirect pages sometimes have blobs of text in "User Messages" (in the admin, in the GBE section) that you may or may not care to change.

The stuff w/out REDIRECT will definitely deserve a solid review - not only could I make a mistake in porting it, but also it's old and needs a re-read.

I *did* update the footer already to be next year's date. :)

**Comment by burlexpo** [comment]
OK.  Where should I go to review these pages? Right now, http://www.Burlesque-Expo.com will still take me to the old site.

**Comment by bethlakshmi** [comment]
https://burlesque-expo.us.aldryn.io

Is the site.  You may have to do password reset.

In migrating Vendor FAQ, I found the hover underline of a link make with the new header font is extremely weird looking - it comes out as an ugly dashed line that is uneven as it seems to fall between the spaces of the letters.  My fast hack was to make the link look like a button - which I found much prettier.

If you don't like it, let me know.

**Comment by bethlakshmi** [comment]
I got the styles set up correctly in the editor.  I also gave the editor toolbar a facelift, so if you are looking for something and can't find it in the text editor, let me know.  Everything EXCEPT the "About" pages is done.

**Comment by bethlakshmi** [comment]
Fixed the cktexteditor - it works now, and has our custom styles (and the normal styles) in it

Finished the last 2 not so visible pages.
Decided not to port secret full of bugs page, because I don't see the bugs, even in the old site.  If we happen upon them again, making another page works.
