### ISSUE TITLE
Class listings don't display teacher names

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#181]
They used to... Now they just display time, title, and location.  I would think the teacher's name(s) would be displayed on the line below the class name and above the location.
<img width="1440" alt="Screen Shot 2021-03-08 at 12 16 57 PM" src="https://user-images.githubusercontent.com/5369404/110356621-740c7800-8008-11eb-9a12-ed397b30f653.png">

**Comment by bethlakshmi** [comment]
If we showed teachers, it would have been on the pre-mobile calendar displays a few years ago.
I can put the typical 1 teacher in easily (and handle a case of more teachers that is a rarity).

I'm hoping you don't want to do moderators/panelists - moderator I could do, 2-4 panelists would be a real estate problem.

Let me know if you want moderators... I'm gonna assume no, and just put in the teachers name (and not label it "teacher")

**Comment by bethlakshmi** [comment]
Hows this?

![Screen Shot 2021-03-09 at 10 21 06 AM](https://user-images.githubusercontent.com/4542707/110494080-3fa8c280-80c1-11eb-9639-41dd8650b256.png)

**Comment by bethlakshmi** [comment]
#183
