### ISSUE TITLE
Volunteer weirdness

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#189]
If I go to the "Review Volunteers" page, it looks like we have one volunteer (Jo Oltman -- see attached).  

But if I go to the [Staffing Report](https://burlesque-expo.com/reports/review_volunteers/event/971) to see what the staff is like, I see a bunch more volunteers (not counting the rehearsal slots; I'm looking at Mr Wrong at Playback and Scarlett Letter as Stage Manager).

Shouldn't they be on the "Review Volunteers" page?

<img width="1440" alt="Screen Shot 2021-05-11 at 11 16 25 AM" src="https://user-images.githubusercontent.com/5369404/117841140-c78a8480-b24a-11eb-8afd-d89770ca0122.png">

**Comment by bethlakshmi** [comment]
They are only in the review volunteer page if there's a need to review them.  Per the new design last year - they only need to be reviewed if they applied to an event that required approval.  On the volunteer calendar, that's any event with a yellow checkbox; on the event scheduling pages, the approval-required volunteer slots are shown highlighted in yellow.  These events require approval - so you'll see the volunteers on that review list.

Everything else - the volunteer signs up, they are signed up - no more approval required.  They show up on all reports, and other management pages as fully signed up (vs. "pending" which is what a volunteer waiting for approval is).

**Comment by bethlakshmi** [comment]
I think this is answered.... closing... reopen if there's another question
