### ISSUE TITLE
20th century font source

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#2]
It seems like it should be free to use 20th century, since I have never had to buy it before... but it's just not working and it doesn't actually seem to be a GoogleFont.

**Comment by burlexpo** [comment]
Here are 3 Google Fonts I like:

https://fonts.google.com/specimen/Vast+Shadow
https://fonts.google.com/specimen/Yesteryear
https://fonts.google.com/specimen/Grand+Hotel

**Comment by bethlakshmi** [comment]
Woot!  https://burlesque-expo-stage.us.aldryn.io/gbe
