### ISSUE TITLE
Reconsider problems with event parentage

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#200]
A few days back, some of our conference cleanup was complicated by the fact that we had orphaned events - in this case, the volunteer events were really a part of a show, but because of how they were cloned, they were all by their lonesome.  That showed a weakness at a couple of places in the system:

1 - Clone event - if the event being cloned has a parent, the user should at least be offered the option to pick a new parent in the cloning process.
2 - Set parent after the fact - if the user didn't set a parent when making the event, they may wish to later... this would also help with the wished for use case to let an event be part of a show and yet have a staff area.  It doesn't solve the whole problem, but it lowers the bar
3 - get a report of volunteer staffing that includes events that are "orphans" - no staff area, no parent event.  Could be a flat list that shows these guys and their volunteers.

I think all three are useful, and will probably do all 3 unless something gets too hard.

**Comment by burlexpo** [comment]
I like all of these options.
