### ISSUE TITLE
Can't publish pages

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#204]
When I try to publish changes to the site after doing a text edit, I get a 500 Server error.  I get the same error regardless of whether I am trying to publish edits to an existing page or if I create a new page and then publish edits.  (I can create a new page without issue).

![image](https://user-images.githubusercontent.com/5369404/118920184-e3092580-b903-11eb-824b-e320588dbe55.png)

**Comment by bethlakshmi** [comment]
me too.  OK, on it.

**Comment by bethlakshmi** [comment]
Fixed it - it was a dependancy issue in Django CMS.  Reset it to a working version and tested on the test site - you should be good to go.
