### ISSUE TITLE
Math Bug

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#220]
If you take a look at the summary of Act Bids and you search for "Stripsee Peel" you'll see her score is 3.0, but if you actually look at her act review, you'll see that her ratings are all zeros except for essay which is a 3.  That means her score should be (0+0+0+0+0+0+0+3)/7 = 0.4285

An "N/A" selection in a category should drop that category out, so that if Stripsee had all "N/A" except the essay, she would have had a 3.0.  But, for example, NA+NA+NA+NA+NA+1.0+3.0 = 2.0, because it's the same as (1+3)/2.

My hope is that this is a pretty simple fix

**Comment by bethlakshmi** [comment]
Got it.  Yeah, it's both showing -- when it should show 0.0 and it's averaging like the 0's are N/A's. 

Oh what a little bugger.  Found it.  Dammit.  0 = False and 0 = Actual Average will get a girl every time.

Working on it.  Need to clear head and move around a bit but I got it.

**Comment by bethlakshmi** [comment]
deployed now
