### ISSUE TITLE
Transparent "Help Text"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#221]
The Help Text on the act review page (the **(i)** ) is transparent -- has no background.  My guess is that this is a style thing.  Assuming this is the same for all the help pop-ups on the site, we should fix this soon.  Especially if it's a quick fix.  Picture attached.

<img width="1440" alt="Screen Shot 2021-06-17 at 11 23 06 PM" src="https://user-images.githubusercontent.com/5369404/122504557-895e4e80-cfc8-11eb-9b48-9529474d23e3.png">

**Comment by bethlakshmi** [comment]
Weird.  This is happening - sometimes.  Everywhere.  I think it's a focus issue - that when your mouse is on the help text, it's solid, when it's not, it's transparent.

**Comment by bethlakshmi** [comment]
Got it - found the style selector that was too specific, and made it right.  This was a database change, now that styles are dynamically calculated, so no code update needed.  Fix is deployed on live now.
