### ISSUE TITLE
Icon Library

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#233]
Can we use this one? https://thenounproject.com/

If not, please let me know what I'm looking for in terms of computer requirements

**Comment by bethlakshmi** [comment]
This is along the lines of the same level of effort in software dev to giving you the ability to stick an image in there.

These icons are in files that you include in whatever you are making.  When I go to one of these icons:
https://thenounproject.com/Iconathon1/collection/redefining-women/?i=2909304

It gives me files to download.


The thing I'm talking about being easy is like this:

Font Awesome:
https://fontawesome.com/v5.15/icons?d=gallery&p=2

- click on an icon and you get to this - https://fontawesome.com/v5.15/icons/500px?style=brands - at the top of that icon, there's instructions to copy this HTML into your page:  

`<i class="fab fa-500px"></i>
`
Which means that all I keep around is a text string.

Simple Line Icons:

https://simplelineicons.github.io/

is similar - the instructions are crude - but you pick an icon and you get something like ".icon-people" - which is saying that you should make html like:

`<i class="icon-people"></i>`

And the icon will work.

In the link you are pointing to, I don't see any such instructions, to use these, you download them all, and then include the PNG, IMG or whatever in your document.  That's basically the same as any photo.

**Comment by burlexpo** [comment]
OK -- so this library should work? https://icons.getbootstrap.com/

If so, it works for me.

**Comment by bethlakshmi** [comment]
yes, that works

**Comment by burlexpo** [comment]
@bethlakshmi OK -- so please install that one.  Do you want me to create a new issue?

**Comment by bethlakshmi** [comment]
verfied it - it's up on live
