### ISSUE TITLE
Double the number of volunteer spots

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#234]
https://www.burlesqueexpo.com/scheduling/show_edit/GBE2021/4613

The sunday showcase shows pretty much 2 volunteer events for every type of volunteer.  One starts at 7:00 or 7:30 PM, the other at 8:00PM.  Is that really what you want???  

This is public right now, so I suggest we fix it quick.  I'm just not sure what you want?  Were you trying to have 1/2 of these be around at rehearsal time?

**Comment by burlexpo** [comment]
I've removed all of these things.  I think that it was some function of me cloning a show or cloning the shifts.
