### ISSUE TITLE
Automatically remind performers to do their act tech forms

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#238]
1. Make it possible for a perform to ack that they won't be at any rehearsal - so they don't get nagged for this.
2. Make an auto reminder that reminds performers to complete their act tech & rehearsal selection.  Our definition of "incomplete" is:
        - rehearsal not booked or not deliberately avoided (item 1 TBD)
        - music is uploaded & has a track title or they have confirmed they don't need music.
        - duration is set
        - prop setup has something in it ("I have no props" is valid)
        - starting position is set
        - primary costume color and feel of act are set
        - pronouns are set
        - intro text is set

That's what makes act tech info complete and if it's incomplete, the performer gets a reminder on their landing page, and the stage manager gets the act showing as incomplete (red) on the dashboard.

The new code will run as a cron job (configurable in frequency on the Divio pages) that mails a template to the performer contact for any act that is incomplete, giving the URL to update the act tech info, and whatever reminder is in the email template.

Some constraints:
- 1 email per act - so if a performer has 3 acts, and none of them have act tech info done, they will get 3 reminder emails.
- 1 contact per act - so troupes of X people have the 1 managing profile contact person - that's who gets the email.
- 1 template for all act reminders.  Not 1 template per show.  And the day of reminders is not connected to the show date - ie, it's not that they get a reminder 7 days before the show in which they perform.  They get a reminder every 7 days if the cron job runs every 7 days.
- after the show has passed, the act no longer gets reminders.  That's subtly different (and better) than the conference being over, since if we move to daily reminders, the Friday Rhinestone Review people won't get reminders on Saturday but the Sunday Showcase people will.

QUESTION:  Should Stage Managers or Staff Leads be able to edit the email template for this? "No" is less work, but right now the people can currently access these templates are:

'Act Coordinator',
'Class Coordinator',
'Costume Coordinator',
'Registrar',
'Scheduling Mavens',
'Vendor Coordinator',
'Volunteer Coordinator'

And none of that really seems to fit.

**Comment by burlexpo** [comment]
Right now, let’s go with less work. 

Since it’s a single email for all 4 shows, it would be weird for all 4 stage managers to edit it.

**Comment by bethlakshmi** [comment]
OK.  How about right now I give it to Act Coordinator as the closest bet.
Also - we have this email opt-out thing - I have 4 categories of email they can opt out of right now - which are described to the user as:
```
    'send_daily_schedule':  '''We'll mail you your schedule for the next day \
        (on Friday, you get Saturday's schedule). This includes any classes \
        you are teaching or have expressed interest in, any volunteer shifts, \
        any scheduled rehearsals, etc. Opting out will disable this \
        feature.''',
    'send_bid_notifications':  '''If you have applied to teach, volunteer, or \
        perform in the past, we may reach out to you to see if you want do \
        one or more of those things again. Opting out will keep you from \
        receiving those emails, but will not prevent you from getting \
        individual emails about your current commitments.''',
    'send_role_notifications':  '''If you have taught, volunteered, performed,\
        sold stuff, or displayed stuff in the past, we may reach out to you to\
        see if you want do one or more of those things again. Opting out will \
        keep you from receiving those emails, but will not prevent you from \
        potentially getting individual emails about your current \
        commitments.''',
    'send_schedule_change_notifications':  '''The GBE system will \
        automatically email you when a part of the expo you are interested \
        or participating in has changed.  Turning off this item will \
        automatically disable that automated notification.''',

```

None of these fit great, but I'm tempted to call it "send_schedule_change_notifications" - since it's related to something they are scheduled to do....?   I could also (easily) eliminate the check entirely from this flow.   I'd just rather not make a special case just for this.

Preferences?

**Comment by burlexpo** [comment]
Giving the edit power to Act Bid Coordinator is good for now.

From the descriptions, it sounds like "Schedule Change Notifications" is the closest fit.  That's fine.

**Comment by burlexpo** [comment]
@bethlakshmi Looks great. Made some minor tweaks.  It's ready to roll.

**Comment by bethlakshmi** [comment]
Noted.  I tried to set up the cron job, and found that the GUI I use lets me do daily, but not every few days.  Cron can do it, the GUI cannot.  I filed a question to the support folks to see if there's a more manual way for me to do it.  If not, I'll add something clever in the code (ie, a state to check "was this sent w/in 7 days?  If so, do nothing").

**Comment by bethlakshmi** [comment]
FYI so you know what's up:
- sent a manual invocation of the email to remind folks about act tech yesterday.  Verified the emails went sent.  Since then, I'm seeing a few password resets.  Can't tell if that's connected, but it seems possible?
- Just set up a pull request to work around Divio's limitation.  It also gives us a way to increase frequency w/out me doing anything - there is now a database setting to specify what day of the week we want the act tech email to be sent.  We can add more rows with days of the week specified to send the email more frequently.  So we can do "only Mondays" to start (or any day, pick your day) and then do anything from 1 to 7 days to scale up our reminder frequency.  Later on, we can turn it off by turning off all days.

**Comment by burlexpo** [comment]
I got my two (one for me as MC of the Main Event, one for me as the head of BeauTease).  I shut off reminders about me as MC (I hope).

**Comment by bethlakshmi** [comment]
Got my weekly reminder settings setup and then setup the cron job. 

The job runs daily at 3:00PM server time (which I think is an hour off our time.

But it only sends the email on Monday.  If you want to increase the # of days it sends email, the setting is here:

https://burlesque-expo.com/admin/gbe/emailfrequency/
