### ISSUE TITLE
Special > Schedule > Conferences

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#240]
This label led to some justifiable confusion, since "Conference" is what we call the classes portion of the whole weekend.

Can we change the label to 

_Special > Schedule > Event Dates_

I _think_ that's clearer... at least someone will see it and be confused in some other way.

**Comment by bethlakshmi** [comment]
It confuses me a bit.  If we do this, we have:

Schedule -->
   - All Events
   - Event Dates

Which seems like - if I can schedule all the events, how is event dates different?

How about "Expo Begin/End"

Or even 

Schedule All Events
Set Expo Dates

As two separate top level options.  Restructuring the hierarchy is not that much more work - especially if I'm only messing with this area.

The core of the difficulty is probably that we use Conference to mean Classes, and Events for individual time blocks w/in the weekend.  So maybe "Expo" is a good word for "All the stuff that happens over the entire weekend?"

**Comment by burlexpo** [comment]
I see the menu listings as being additive — like you’re stringing together words in a sentence.

So Schedule > Expo Dates is a fine label. Let’s leave the other one alone

**Comment by bethlakshmi** [comment]
Will do.  I found some mess I made with the hotfix, so will fix this too,
with some updates I want to post soon.

**Comment by bethlakshmi** [comment]
Deployed the comp use case on live.  Leaving this open to do the rest someday, maybe.

**Comment by bethlakshmi** [comment]
Deploying fix on live right now, along with some fixes to my hotfix.
