### ISSUE TITLE
Make a blog/newsfeed style thing in Django-CMS

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#242]
based on conversation, @burlexpo wants a publication capability with features like (maybe did not get all of them):
- ability set timed publications for the future
- a feed-style summary presentation with rolling updates (newest to older) that gives a summary few bits of text, header, publication date, etc.
- ability to link in images

**Comment by bethlakshmi** [comment]
I think I found one in the Django-CMS pantheon:

https://aldryn-newsblog.readthedocs.io/en/latest/introduction.html

Example of it at work:

https://www.django-cms.org/en/blog/

**Comment by bethlakshmi** [comment]
Nope that failed.  Finally figured out it's deprecated and it's packages are too old to work

Now trying this:  https://djangocms-blog.readthedocs.io/en/latest/installation.html

**Comment by bethlakshmi** [comment]
Notes (these won't make sense for a bit, but I need a place to take notes):
- there's two kinds of "published" - a checkbox on/off and dates.  If dates are used, the checkbox still needs to say "published"
- categories and tags don't count an article unless the check box is on and if there are dates, we are currently w/in the dates.
- the Blog menu item, if published, shows ALL arcticles, even those not published (weird, needs more research).
- neat feature - /sitemap.xml - to help with SEO
- still working out user features in my local - I suggest we make a group with a distinct set of privileges.  Users will need Blog create/edit/delete/publish and then page create/edit/delete/publish

**Comment by bethlakshmi** [comment]
OK - it's live with a sample of stuff in https://burlesque-expo-stage.us.aldryn.io

I have. path to giving users access, but I'm going to hold off until you get a chance to play with it, and tell me whether or not you can use it.  If you can't, let's talk about what other requirements you need....

**Comment by burlexpo** [comment]
OK -- I'm clearly missing something.  I can do everything **except** create the body of the article...

**Comment by bethlakshmi** [comment]
Ugh - the one you liked - Zinnia - https://github.com/Fantomas42/django-blog-zinnia/issues

Seems to have been abandoned for a year.  The reason the doc site wasn't working is that the domain is likely lost and being reused by malware.  I have dug up some of the older versions of the doc, and I can probably get it up and running, but I'm a bit worried on the long term maintenance.

That said, this blog comes up all over the place as a recommended Django Blog package, so there is popular vote on that.

And I can't find another good option.

**Comment by burlexpo** [comment]
I’m confused. Which blog comes up as recommended all over the place?

**Comment by bethlakshmi** [comment]
The Zinnia blog you and I looked at on Friday.  When I look for "Django
blog" on Google, I get that a fairly large number of times, and yet their
Git Repo hasn't been touched in a year, and they don't have a release for
the status quo recommended Django version.

**Comment by bethlakshmi** [comment]
redundant to #418
