### ISSUE TITLE
Allow people to use their e-mail address for login?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#26]
Many sites that I'm on these days have done away with the "user name and password" login combination in favor of the "email address and password" login. Some places allow you to use either one.

Can we do that? If we can (easily) we should do it before the launch of the new site.

**Comment by bethlakshmi** [comment]
I'm confused, we did that years ago with https://github.com/bethlakshmi/GBE2/issues/1090

And I just double checked to make sure it's still all good.  I can login with EITHER "betty" my username -OR- the email address attached to my account.  You can too... you are you at bostonbeautease in the system...

**Comment by burlexpo** [comment]
Oops! never mind....
