### ISSUE TITLE
HR do not display on page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#27]
<img width="1440" alt="Screen Shot 2019-11-24 at 8 29 09 PM" src="https://user-images.githubusercontent.com/5369404/69594760-5c53e080-0fcb-11ea-9170-3b1eb4967b93.png">
I can use the "insert a horizontal line" function in the editor and it shows up in the editing window, but it doesn't show up on the website.  Tested this with Chrome and FireFox.

**Comment by bethlakshmi** [comment]
A quick look says that when I press the Horizontal Line (see red circle):

<img width="1440" alt="69594760-5c53e080-0fcb-11ea-9170-3b1eb4967b93" src="https://user-images.githubusercontent.com/4542707/69901380-e4106500-13a6-11ea-94b5-c34527b30de8.png">

Then as you say, it appears in the editor, but when you save and publish... not so much.

Looking at the HTML, I see the <hr> tag - it's there!  So this isn't the editor, this is our styles that are screwing with it...

![Screen Shot 2019-11-30 at 7 24 47 PM](https://user-images.githubusercontent.com/4542707/69901407-2e91e180-13a7-11ea-8492-76f8e4c2af06.png)

I think I see where the style problem is....  if you need it right this minute - add this to the <hr> tag:

style="border-top: 1px solid #333;"

But should get fix up pretty quickly.

**Comment by bethlakshmi** [comment]
Deployed fix directly to live server as hotfix.  Back merging to develop for consistency.

**Comment by bethlakshmi** [comment]
Totally fixed - got the live site to redeploy.  Did not test there as I don't want to mess up what you are working on.

But did test in test server - see here:  https://burlesque-expo-stage.us.aldryn.io/main/

**Comment by burlexpo** [comment]
Yup.  Totally fixed.
