### ISSUE TITLE
Password reset email link doesn't work

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#280]
It works for our native hosting DNS (https://burlesque-expo.us.aldryn.io/) but not for our published, redirected DNS burlesque-expo.com - which is what the email actually sends to users, because it draws the hostname for the URLs from our site settings, and we want the default URL to always be our nice pretty registered one.

This is all customizable django code that I did the bare minimum of branding to years upon years ago, so I'm pretty rusty at it, but it can probably be fixed with some elbow grease and swearing.

Another option is to provide the change password account management page that django builds for easy enabling, and that way, if the user HAS their password, they can change it w/out going through the email path.  That doesn't help users who legit forgot their password, but it's a nice usability win.

**Comment by burlexpo** [comment]
@bethlakshmi wondering where we are on this.  It seems like it's going to come up again soon.

**Comment by bethlakshmi** [comment]
duplicate of #339
