### ISSUE TITLE
Dates for GBE14

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#281]
The dates are

- Wednesday, May 3
- Thursday, May 4
- Friday, May 5
- Saturday, May 6
- Sunday, May 7
- Monday, May 8

If we can update the dates in Django, it'll help me start getting things set up.

**Comment by burlexpo** [comment]
Our date model is changing at least for this year 

Wednesday, May 3 - private (set-up)
Thursday, May 4 - public (show in the evening, maybe some event before or after it, need reg desk to be open)
Friday, May 5 - public (shows in the evening, maybe some classes or special events)
Saturday, May 6 - public (full deal: shows, events, classes,
Conference, exhibit hall)
Sunday, May 7 - public (no show but events, classes,
Conference, exhibit hall)

**Comment by bethlakshmi** [comment]
![Screen Shot 2022-07-19 at 9 56 05 PM](https://user-images.githubusercontent.com/4542707/179879172-8ca4c5b3-ca79-410e-8e6a-dd1ebc22d4dc.png)

fixed.

Gentle reminder - if I didn't do something right, it helps if you reopen the ticket.  I just happened to see the response, and remembered.
