### ISSUE TITLE
www.Burlesque-Expo.com points to TheArtsNexus.com

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#282]
I don't know if this has anything to do with our certificate or not -- which may have expired.  I'm working on it.

**Comment by bethlakshmi** [comment]
Looks like you fixed it.  It wasn't a change on my end.

**Comment by burlexpo** [comment]
Yeah, it had something to do with our SSL certificate being shared between two domains or something.
