### ISSUE TITLE
What are the rooms for Old Town Hall?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#284]
We have a new site and a new set of rooms.  Tell me the rooms and I'll manually enter them.

**Comment by burlexpo** [comment]
Theatre
Meeting Hall
Class 1
Class 2
Reg/Info Desk

--
Team BurlExo
Burlesque-Expo.com
#BurlExpo

**Comment by bethlakshmi** [comment]
Done
I also embedded a Google Map for all of them, which will show up on event listings.
