### ISSUE TITLE
Sit with Betty and Set up Payment 

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#288]
This blocks act submit go-live

Last year we had:
![Screen Shot 2022-09-22 at 9 41 10 AM](https://user-images.githubusercontent.com/4542707/191762979-5ba95fc8-3645-4200-8f78-d50d2399f530.png)

For act submit.  Do we want the same thing?

The biz logic for what we did last year, and how this all works are complicated enough that I think it warrants us sitting together and looking at it.  We have stuff like:
- donations - which we set with a validity date
- a regular fee - which is currently hidden (??)
- comps 
- and early acceptance fee...

So I can't quite figure out what all we were doing nor what we want to do (and on what dates) this year.

**Comment by bethlakshmi** [comment]
The immediate needs are done:
- set up the donation of a minimum of $5, it will go live on 10/1 and last through 10/31
- And a second fee that goes live on 10/1 and NEVER ends that sets the Act Fee (not a donation) to $7 (that was last year's precedent...).   It's effective invisible until the first donation period expires, then it takes effect.

I didn't submit it, but it seems to display as desired.

Leaving open until @burlexpo confirms the 11/1 fee is all he needs and the value he wants.  But that gets us past this milestone

**Comment by burlexpo** [comment]
Confirmed.  That'll get us through until Nov. 1 and I can change my mind before then if I want ;-)

**Comment by bethlakshmi** [comment]
Reminder @burlexpo of this.

**Tomorrow** Act Fees go up from voluntary $5 to mandatory $7 and then stay at that rate forever.

If you want anything else to happen - go to https://www.burlesque-expo.com/ticketing/ticket_items/?conference=GBE2023&open_panel=act&updated_tickets=[358]&updated_events=[]

or ask me to do something.

**Comment by burlexpo** [comment]
It’s a mandatory (and fixed) $15. No option to go higher or lower

--
Team BurlExo
Burlesque-Expo.com
#BurlExpo
