### ISSUE TITLE
Refactor first time data entry to simplify it

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#295]
This could/should really be a few tickets, but I think I can handle it as one as these are all in the same spirit:
- ~~On the Create Account page - remove all fields except Email (username = email), password X 2, name (new field for this page, it's the "display name"), and the I'm not a robot thingy.~~
- Remove Update Profile as a required flow for bidders - it's still around it just doesn't get put here.  The 1 required field will be "name" which is given on Create account.
- On Act and Class - add phone number as a required field
- ~~Remove "other performance opportunities" from the act bid.~~ done via #290 

That should be all the field changing must-haves prior to act/class bid launch

**Comment by burlexpo** [comment]
Is there a way to require phone numbers from Volunteers as well? I understand it's a different flow.

**Comment by bethlakshmi** [comment]
Got the account create page working:
![Screen Shot 2022-09-30 at 5 28 33 PM](https://user-images.githubusercontent.com/4542707/193358896-77da05da-caf0-4421-9fad-082594dbe0a8.png)

This is useless w/out moving phone # to act & class, but this is 1/2 way to easier bidding.

@burlexpo 
Posting here so I can get feedback on text that I ad-lib added.
Also note:
- if they have originally requested a bidding thing, they will go from this page to the big page
- if they are just registering, they go to the profile update page... because that's how it originally worked, and I couldn't see a reason to change.

**Comment by burlexpo** [comment]
Ad-lobbed text looks fine to me

**Comment by bethlakshmi** [comment]
also did an update to the phone message - 'For the Expo only, in case we need to reach you.'
