### ISSUE TITLE
Change "Your Account" to "Your Dashboard"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#302]
I use the term "Dashboard" pretty consistently through the site.  Can you change the menu item "Your Account" to read "Your Dashboard"?

**Comment by bethlakshmi** [comment]
Yes - that's easy - will fold it in with some similar updates in the next batch later this week

**Comment by bethlakshmi** [comment]
Do you want a change for the subitem "Your Expo"?  that's what gets you to /gbe

**Comment by burlexpo** [comment]
I think, if possible, the top level menu item should say "Dashboard" and should be the only item and "Update Your Profile" should be relocated to a button on the dashboard page.  And "logout" should be an icon in the header (near the "Tickets" and "directions" buttons).  If possible.

**Comment by burlexpo** [comment]
All three options, I think.

- change "Your Dashboard" to "Dashboard"
- change "The Conference" to "Conference"
- move the 2021 Photos link to a sub menu somewhere

I believe moving photos and changing "The Conference" to "Conference" are on me.

**Comment by bethlakshmi** [comment]
OK.  Changed Dashboard.
The other two are in the CMS system
