### ISSUE TITLE
"Bid Control for Coordinator"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#310]
On the act review page, we currently use the language "Bid Control for Coordinator".  I suspect this same language is used on Class Review, although I don't know if it's actually the same label (I.e., can they be changed independently).

Maybe we want to change it to something like "Act Status" or "Act Decision" to reflect current language use?

**Comment by bethlakshmi** [comment]
#325 - I hit all the titles in that area, and make them all configurable.
