### ISSUE TITLE
Copying "Main Event" fails

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#315]
<img width="1680" alt="Screen Shot 2022-10-10 at 8 06 15 PM" src="https://user-images.githubusercontent.com/5369404/194970331-7e80444f-3046-4ce3-a702-21116b99a53e.png">

Went to https://www.burlesque-expo.com/scheduling/copy/4590 to create a copy of last year's Main Event and all releated sub-events into this year's Saturday (May 6), and got a Server 500 error.  It seemed to create an event (there's one there now), but it also threw the error.

**Comment by bethlakshmi** [comment]
closing this, see #313
