### ISSUE TITLE
Add "Social Media" fields to profile and display (Pt 1)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#343]
Add some fields to the Profile section that link to people's social media.  I'm thinking that we do something like have 5 short text fields, preceded by text that says
_**Your Links** Use the fields below to link to your personal website, social media sites, or for a financial link where audience members can send tips.  The first three will be displayed when you perform; all of them will appear on your profile on the site if you are accepted._

And then have however many they fill out display as part of their bio. i.e.

_**Scratch** Scratch is very tall and has a ponytail and is really bad at writing biographies.  He is probably too fond of cheese and sex parties._

_www.BostonBeauTease.comn
www.instagram.com/the_mr_scratch
www.facebook.com/whatever_

**Comment by bethlakshmi** [comment]
Easy enough to make 5 fields for this.  But a couple questions:

- I'm not sure what "_The first three will be displayed when you perform; all of them will appear on your profile on the site if you are accepted_." means.  When a performer is accepted into a show, they have 1 place where stuff shows up (the show page, with a small bio and a link).  When a teacher is accepted, there is a teacher's bio page, with pretty similar info for each teacher.  There is no per-performer/teacher profile page, other than the editable page that is only viewable to that person.  So I don't know what "all of them will appear on your profile" means....?
- Should I screen for duplicates?  If I do, shall I just store each unique URL and not bother them with fixing their data?  Alternately, I can tell them they messed up and make them correct it.

**Comment by burlexpo** [comment]
What I mean is while a performer is on stage, we’ll display a slide with their name and the first three social media links. All 5 media links (if they use all 5 fields) get displayed on the site after their bio. When you say “screen for duplicates” do you mean that I (Scratch) have put “www.BostonBeauTease.com” in two of my fields, or that you and I (Scratch and Betty) have both put “www.BostonBeauTease.com“ in one of our fields?--Team BurlExoBurlesque-Expo.com#BurlExpoOn Dec 27, 2022, at 12:05 PM, bethlakshmi ***@***.***> wrote:﻿
Easy enough to make 5 fields for this.  But a couple questions:

I'm not sure what "The first three will be displayed when you perform; all of them will appear on your profile on the site if you are accepted." means.  When a performer is accepted into a show, they have 1 place where stuff shows up (the show page, with a small bio and a link).  When a teacher is accepted, there is a teacher's bio page, with pretty similar info for each teacher.  There is no per-performer/teacher profile page, other than the editable page that is only viewable to that person.  So I don't know what "all of them will appear on your profile" means....?
Should I screen for duplicates?  If I do, shall I just store each unique URL and not bother them with fixing their data?  Alternately, I can tell them they messed up and make them correct it.

**Comment by bethlakshmi** [comment]
Note to self - order matters - track it and always display that way.
Duplicate - throw a blocker error and tell them not to.
Input = 
- pull down for label - website, FB, Insta, Venmo, paypal, ticktock, cash app, youtube - make type unique
- and an input (not a link) - username or @username, the website is a URL

**Comment by burlexpo** [comment]
Add Twitter as an option? Do people still use it?

**Comment by bethlakshmi** [comment]
Good question.  I was just pondering the same after our chat...  it's the 15th most popular according to Hootsuite (???), but doesn't get a mention by [Shopify](https://www.shopify.com/blog/most-popular-social-media-platforms) - fully admit I'm biased on that, but they do do their research...

Also -- what about linked in?  For computer geeks, this is the must-have.  But I see a certain amount of Burlesquers using it too... ?  Definitely my sample size is too small.

In other notes, I'm pondering how far to take an ideal experience here...

Things I'm finding - for our current preferred account types:
- Venmo - has a url format, ending with the @username format thing
- Paypal - same
- FB also has a username, but there's a variety of options - pages vs. users, like vs. follow.  Been playing with it for a while, and nothing sticks out as the easy way - I think for FB, we should just require a valid URL.
- Tiktok - has an @username URL format, with a follow button on it.
- Cashapp - same
- Instagram - same
- YouTube - channels have that same @username format at the end.

So, I propose:
- for most things, the input is "what is it (Instagram/Tiktok/Venmo/etc...)" dropdown and a text field for what is the username?  And I build the URL.  I'm thinking a format like the pic below.
![Screen Shot 2022-12-29 at 4 10 49 PM](https://user-images.githubusercontent.com/4542707/210014334-88b85112-a8e4-4f23-8eea-fc7fd2873335.png)
- for FB & websites - you give us the whole URL.  And for these, you can have more than 1 - so if you have an FB profile and an FB page - you can do both.  And if you have a website and some other format (like linked in) you can post the full URL and use it.

**Comment by bethlakshmi** [comment]
Deployed!  Note - the change to keep the user on the page while editing is NOT done.  Still working on that, but assumed it was not a full on blocker.
