### ISSUE TITLE
Fix "Submit Accepted Act"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#345]
The "Submit Accepted Act" button does not allow you to submit a paid draft for the performer to complete later.  It allows you to submit an incomplete act and automatically accepts it for the first show.  

I think we need a halfway step here such that we can create an act and submit it, but some still has to assign it to a show and accept it.

**Comment by bethlakshmi** [comment]
Instead - fix this so - the submit accepted act, first step puts the act in "submitted" ("needs review") state.  Then kick to the review page so it can be cast.

Having it accepted and yet not cast in a show is weird.

Also - add button for comp a fee to the same place.  And add docs for what is needed for create a comp ticket (needs special flag).

**Comment by bethlakshmi** [comment]
Pushing to production now.  Should be deployed in < 10 min.  Will check it later.

**Comment by bethlakshmi** [comment]
Fixed the flow, as well - that's still in PR, but most of this fix is online

**Comment by bethlakshmi** [comment]
just closed pr to fix flow.  deploying now.
