### ISSUE TITLE
Act submit for troupes

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#346]
Make an explicit question - are you submitting for an individual or a troupe?
then kick them to the right place.

Maybe also tune to make the first member (the submitter) in a smoother way.

**Comment by bethlakshmi** [comment]
This will be me learning Javascript a bit, but I'm thinking....

<img width="1056" alt="Screenshot 2023-07-16 at 11 05 20 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/baf9801f-a69f-46f7-aadf-662c06fbcb7e">

I can do that, so that it's all 1 form - both solo and troupe - with only the "what other members are there?" being included.

For acts and in the bios part of the home page, this is how "create new" use case will always work.
For classes, it'll still need to work the way it does now - no ability to add multiple people, since we require only single teachers for class bids.

And once they choose solo/group, it's permanent - they can't change a given bio from solo to group after making it.  But they can delete a bio that isn't involved in anything and make as many new ones as they like.

**Comment by burlexpo** [comment]
_For classes, it'll still need to work the way it does now - no ability to add multiple people, since we require only single teachers for class bids._

How do handle situations where two (or more) people are teaching a class together?

**Comment by bethlakshmi** [comment]
OK, based on today's discussion, I think I'm doing this differently:

1 - leave the "Create Bio" section as is, and remove the "troupe" tab.  We can/should add intro material to this saying something about how this should be the person or performance group as a whole, and that it can be edited later, too.

2 - Add to the [act creation](http://0.0.0.0:8000/act/create) form - # of performers in Act, and a text box for performer names.  I'm thinking of adding it right under Act Duration.  And making it required (but not for a draft).  It's just an integer, greater than zero.

3 - move Troupe member entry from the Bios, to the Act Tech form.  It can be edited as long as the Act Tech form can (until the conference closes).  The Troupe member entry should always cap the # of people to the size of the original act application, though.  And that number isn't part of act tech info editing - in other words, if the # of performers increase, then act/troupe contact person should contact us and let us know.

4 - Consolidate Bios even further - there are not 2 buttons/tabs any more - just "Bios"

This should end with no other change to emails, attendance at expo, etc.  The refactor I did in June, already set up the relationship of:
- Troupe Bio ---> set of People gets created/changed.  The set of people has a pointer connecting it to the troupe bio.
- When an Act the troupe is bidding is booked for a show or rehearsal, that set of people is booked for the show or rehearsal with a pointer to the act as part of the commitment.

So the real change here is that instead of editing a troupe's membershig (so going Troupe Bio --> set of people), we're editing the act's membership (act --> set of people) and making sure that every time an act gets accepted for the first time, it gets a new set of people.

There's some sanity checking to be done and thought out, for example:
- when a troupe contact proposes an act in a second year, should the act tech info offer the members from last year as part of the act tech form (assuming the act is accepted)?
- is the act tech info form considered "complete" if the # of troupe members enrolled is less than the number proposed in the act?
- should we email troupe members if they are added/removed from the act tech info form?

**Comment by bethlakshmi** [comment]
I realized Bios that are troupes or soloists are going to need some special handling in the logic here and there, so I left the "multiple_performers" field in the Bios so I'd still have that hook.
But I made it explicit:
<img width="865" alt="Screenshot 2023-09-06 at 10 03 23 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/ea7f483f-8872-423d-bfcb-b9ebbb768f7b">

**Comment by bethlakshmi** [comment]
OK, got the act tech info troupe update done:

<img width="1214" alt="Screenshot 2023-09-07 at 9 02 05 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/c097ea75-0761-4545-b955-131acea5bed3">

I decided to put it in the same section as booking rehearsals, because both rehearsals and the list of performers are schedule related.  Also - that puts it at the start of the work to let the act/troupe contact person know that they need to to this leg work.

The message shown here is my default wording.  It will be editable in user messages.  The last sentence "Choose up to X performers" is hard-coded wording but with a dynamically generated # which is also validated on the form.

@burlexpo let me know if any of these layouts doesn't look good to you.

**Comment by bethlakshmi** [comment]
See #516 but it's a separate PR.  The code is now live on the site.
