### ISSUE TITLE
Need separate templates for "Compete" and "non-compete"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#349]
People cast in the Main Event are being cast as either part of the Exhibition or the Competition.  Right now, you get the same email no matter what role you're cast in.  

I actually think the easiest way to do this is to treat them as two separate shows on the same night -- unless you have a better idea.

**Comment by bethlakshmi** [comment]
I don't have a ready made answer.

My write-some-code plan would be:
- make two roles (competitor and exhibitor) for the event (_doable today_)
- make the automatic email sender sensitive to the roles (**new work**):
    - if a template exists for a role, send the template for that role.
    - if no template has been made for a given role, send the default for casting an act (unique per show)
- make it possible to create a template for a show + role based on a current show's template, on the manage->email templates page, you'd be able to copy a template for a show and say what role it's for. (**new work**, lower priority, as this would be available in a manual hackable way in the admin, immediately w no work on my part)

We talked yesterday, but documenting for sanity - if we go the quick-fix route of just making 2 shows, we have:
- 2 places for the crew to look (the act tech pages are show by show)
- 2 different rehearsal sets - a rehearsal is 1:1 with a show.  We can book 2 slots at the same time, but we can't control the pacing of signup in any unified way.  And the stage manager will need to look 2 places to see all the people showing up that hour.
- performers see 1 show - either the early 1/2 or the later 1/2 - which could cause confusion on show start/end time.
- ticketing can be 1 ticket for both events, but both events show up on the calendar.
- we would set up volunteer shifts off of 1 show and make them the full show length

**Comment by burlexpo** [comment]
I currently have it set up as two shows.  I understand that this may lead to some more work for the SM.  I think we can manage the rehearsal slot issue by simply making the 4pm and 5pm slots available to the Exposition and the 6pm slot available for the Competitors.

I did notice that with the existing email templates there's an "if" statement I never use -- {% if show %} Some text {% endif %}.  I neve ruse it because I'm either writing to accept them for a show or not.  I'm not using the template to automatically generate the letter for me.  That said, could we use similar logic to insert a specific paragraph based on role? i.e.,

Dear {{name}}

{% if competition %} Dude! You're a competitor!! Here's some info about that.  {% end if %} 
{% if exhibition %} Dude! You're an exhibitionist!! Here's some info about that.  {% end if %}

**Comment by bethlakshmi** [comment]
We could, actually! - "show" is the object for the show, so you could do:

{% if show.title = "The Main Event - Competition" %}Dude! You're a competitor!! Here's some info about that. {% end if %}
{% if show.title = "The Main Event - Exhibition"  %} Dude! You're an exhibitionist!! Here's some info about that. {% end if %}

But since there are two different shows, you also should get 2 different act accept email templates.  The template gets made when the first act is accepted.

That does raise a 3rd alternative - I could send other data to the template (like the role they have in the show) - which could be used in the logic of how the template gets built.  That would be an alteration to my previous proposal that is a bit less work, since it's really just adding an argument to existing code.

**Comment by bethlakshmi** [comment]
OK, doing that was REALLY fast - partly cause I just looked at the code a bunch.

It's in PR.  

I also gave a look to how we use casting - we do section out performers by "Regular Act" and "Non-compete" - both are treated as non-special (smaller images on page), but there are 2 sections.  Other than that, they aren't any different.  There is no mention of the casting in the act tech dashboard at all (is that a bug?)

**Comment by burlexpo** [comment]
_That does raise a 3rd alternative - I could send other data to the template (like the role they have in the show) - which could be used in the logic of how the template gets built. That would be an alteration to my previous proposal that is a bit less work, since it's really just adding an argument to existing code._

That's not a 3rd alternative -- that's what I was suggesting.  ;-) When I use Mail Merge in Word, I can do a thing where it inserts a paragraph dependent on the input in a field -- hidden or visible.

Buit I think you not only have figured out how to do this, you may have implemented the fix already.

**Comment by bethlakshmi** [comment]
posting on live tonight

**Comment by bethlakshmi** [comment]
FYI - updated example in production, and added documentation to both versions of main event.

**Comment by bethlakshmi** [comment]
Done messing with anything but template documentation now

**Comment by bethlakshmi** [comment]
Also - I was wrong.  You CAN generate a template w/out casting an act.  

1. Go to https://www.burlesque-expo.com/email/list_template
2. Pick the template you want to mess with (all shows will automatically be shown!, even if they don't have any templates yet)
3. Mess with the template.
4. Save it.

Voila!  Template!  And you don't need to cast anyone.

I did it with all of this year's templates so they are all there.  And I put updated docs for all of them.
