### ISSUE TITLE
Adding "Approve" after Vol Slot is Created

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#358]
During the creation process of scheduling a volunteer slot, you are given the option of checking a box which says 'Approve', which indicates the a potential volunteer requires approval before a being assigned to it.

However, if I create a volunteer slot and forget to check that box, when I go back and Edit the volunteer shift later, thwere is no place to add that information

**Comment by bethlakshmi** [comment]
![Screen Shot 2023-01-06 at 7 18 40 PM](https://user-images.githubusercontent.com/4542707/211121174-a8eb543b-0153-4556-86a6-cee772c952e6.png)

I'm confused.  This is a screen shot and the orange circle is what I think you need to do to get what you want.
