### ISSUE TITLE
Pronoun info and display

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#367]
Two thematically related tasks:

1) We currently ask for pronouns on Act tech info.  Can we instead ask for it as part of persona info  I think my preference is that we do radio buttons:  He/Him; She/Hers' They/Theirs; Other [with a text field to specify]  It would be great if this was done before Feb 4

1a) Pass the pronoun info along to act tech (for the MCs) -- this doesn't need to be done until about a week before the Expo (May 1)

2) Can we print the pronouns on the badge in small print? This needs to be done before badge printing is done and is tied into a different tickets.

**Comment by bethlakshmi** [comment]
Do you want me to pull it from act tech or have it both places?  I think it's a bit easier to pull it, but don't feel strongly.

**Comment by burlexpo** [comment]
Unless it's a major PITA, I think it's better to attach it to a Persona and push it to Act Tech.  That way we get the info for people who don't have Act Tech (like Teachers).

**Comment by bethlakshmi** [comment]
When you say "push it to Act Tech" - do mean leave it on the act tech submission form?

Also - we have pronouns showing on the per-act details page:

https://www.burlesque-expo.com/reports/acttechinfo/detail/1415

![Screen Shot 2023-01-24 at 9 21 40 AM](https://user-images.githubusercontent.com/4542707/214319447-0e29a742-e357-44e1-a0f7-388f09fb6288.png)

Do you want it elsewhere?  Could put it on the summary page?
And do we want it anywhere class-wise?  There's not really a summary list like this for classes.

**Comment by burlexpo** [comment]
Right now, we gather pronouns when people fill out their Act Tech form, which means only people who have an Act Tech form get to tell us what their pronoun preference is.

I want to gather the information as part of the account creation process, and then share that information with any Act Tech forms associated with that account.  That way we know the pronouns for people other than just performers.

**Comment by bethlakshmi** [comment]
We've deployed this today
