### ISSUE TITLE
Name Badges

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#368]
Related to #367 

Develop printing templates to print on https://www.namebadgeproductions.com/product/5341/4-x-3-double-sided-cardbadge-500-pack

Front has
- GBE artwork
- Name of choice
- Pronouns
- type of ticket and obvious graphic icon

N.B.: these are small than the Arisia badges.  What info do we want to put on the back? Boilerplate like Arisia did? Or a schedule?

**Comment by bethlakshmi** [comment]
I think we actually accomplished this?
