### ISSUE TITLE
Syntax for "Feature"-dependent messages

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#369]
You said that this is the syntax I should use something like

`Dear {{ name }},Congratulations! Your act, {{ bid }} was cast in the competition portion of The Main Event! Does it say "Woohoo! This works!" Below this line?
{% if casting==feature %}
WOOHOO! THIS WORKS!
{% endif %}
If so, you're a big goddamn hero.`

But when I put those lines in – either in the HTML field or the plain "Content" text box, I get the error
`Could not parse the remainder: '==feature' from 'casting==feature'`

Please advise

**Comment by bethlakshmi** [comment]
Fixed, with additional commentary in #349 - and I added docs to the current shows.
