### ISSUE TITLE
Vendors can't submit

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#37]
I was contacted by Renee Mallett, who has paid her vendor fee but still cannot submit her vendor application.  Her business name is "Amaranth & Rue"; I can see she has created an application and that she has paid a vendor fee.

**Comment by bethlakshmi** [comment]
Are you sure that her timing and your checking are aligned?  I just made myself a fake purchase of the same thing she did and everything worked.

I see all the settings look exactly right, and I see the purchase under her account exactly where it should be.  Is it that she didn't wait 1/2 an hour between purchase and trying to submit??

**Comment by burlexpo** [comment]
The problem is she says she can't submit.  If I look at her account, I can see she has a vendor fee (those were the ones I synched by hand), but if I look at http://burlesque-expo.com/vendor/reviewlist the only vendor I see who actually submitted is you.  I was going to try the _impersonate_ function, but I can't find it anymore...

**Comment by bethlakshmi** [comment]
OK.  I managed to pull a copy of the live DB onto my local dev enviroment.

I hacked Miss_Rue's account, and changed her password.  Then I logged in exactly as if I was her.

I submitted the vendor app just fine.

I think this is a timing issue... that she didn't have a transaction logged in our system when she had the issue.  Now she does.

**Comment by burlexpo** [comment]
OK.  I wrote to her.  This may just be bad timing; this may be PEBKAC.

**Comment by bethlakshmi** [comment]
Closing... we can reopen if need be when other info is available.
