### ISSUE TITLE
Tickets are Ready to Go

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#370]
I've created all the tickets and I'd like to the API set up so I can sync them with the site.  I don't know what info you need, exactly.  I think we just need to change the Organization to "Professional Burlesque Society".

**Comment by bethlakshmi** [comment]
Oh hey!  I wrote this down back when I knew how it worked!  Go me!!

https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/wiki/Ticket-System-Integration#setting-up-eventbrite

**Comment by bethlakshmi** [comment]
I don't have access to your Eventbrite account, but if you can't get these instructions to work, email me an account and password and I'll try.

**Comment by burlexpo** [comment]
Done ands live on the site
