### ISSUE TITLE
Syntax for Bootstrap Icons

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#373]
According to our documentation, when creating the ticket listings that display on the ticket sale page (https://burlesque-expo.us.aldryn.io/ticketing/), I can use icons from either  https://simplelineicons.github.io/ or https://icons.getbootstrap.com/ 

The syntax for SimpleLineIcons is "_icon-icon_name_" but no matter how I juggle the syntax for https://icons.getbootstrap.com/ I can't get them to display.

**Comment by bethlakshmi** [comment]
The trick is to use everything inside of the class="" thing, so if you have:

<i class="bi bi-arrow-left-right"></i>

Then you just need to put in 

> bi bi-arrow-left-right

No quotes, just that stuff.

**Comment by bethlakshmi** [comment]
Todo:
- upgrade bootstrap
- upgrade the comments to add clarity
