### ISSUE TITLE
Editable Text on Ticketing Page?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#374]
There's some lead-in text on https://burlesque-expo.us.aldryn.io/ticketing/  It's out of date and I'd like to change it.  I can't figure out where/how to do that.  If worse comes to worse, I can send the text to @bethlakshmi and she can edit the page, but that seems like something we should fix (have fixed?)

**Comment by bethlakshmi** [comment]
https://www.burlesque-expo.com/admin/gbe/usermessage/179/change/?_changelist_filters=view%3DListPublicTickets
