### ISSUE TITLE
Add a name when sending email?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#375]
RIght now, when sending email it seems to come from "Mail", which is likely to get lost in people's email boxes.  Is there a way to either 

- change it so all email comes from "Team BurlExpo" regardless of the email address associated with it
- create a table (editable by an admin) that specifies which names go with which addresses (1)
- add a field to specify the return name

My guess is the first option is the easiest, so if that's something that can just be done by adding a line somewhere, let's do that and worry about variables or configuration later

1 - Not every user who can send email can change the "From:" address (in fact, most can't).  SO we could set up a table somewhere on the site or the Admin pages which does something like this:

| Email                                                  | Name                      |
| RegDesk@Burlesque-Expo.com     | Registration            |
| Mail@Burlesque-Expo.com             | Team BurlExpo       |
| Betty@Burlesque-Expo.com           | Betty Balize            |

**Comment by bethlakshmi** [comment]
Yeah, I suspect 1 is easiest.  Will do for both contact bidders/roles and email templates.

Long term, I'd like to:
- when it comes from an actual user, use their display name.
- for privileged users - let them give us both fields, and default it to "Team BurlExpo".
- for templates - give both fields, default to "Team BurlExpo".

**Comment by bethlakshmi** [comment]
Done!  Went in same time as email waitlisted acts per show
