### ISSUE TITLE
Move the "Action" Buttons to a row at the top of the dashboard

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#377]
Make the dashboard look like this, please
![Proposed Dashboard copy](https://user-images.githubusercontent.com/5369404/213829975-4b58d4aa-2554-4290-87ae-1345cb9c3191.jpg)

**Comment by bethlakshmi** [comment]
#378 - PR is ready, can probably pull tonight

**Comment by bethlakshmi** [comment]
deploying now
