### ISSUE TITLE
Act & Vendor payment details need update

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#38]
The text is hard coded to say "wait 5 min, if it doesn't work call us"

With the timing set to every 30 minutes, that advice leads to a lot of frustration.  Change the text.

**Comment by burlexpo** [comment]
Change it to say, "Getting your application fee into our system can take up to 60 minutes.  If you still cannot submit your application after an hour, please contact us". (and make _contact us_ a link to the contact page).

**Comment by bethlakshmi** [comment]
Done!
