### ISSUE TITLE
EmaiL: Wait List - Show?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#382]
RIght now we send show-specific email when someone is accepted (i.e., there is separate templates for "Accepted - Tha Main Event" and "Accepted - The Burlesk Bordello")

I think I'm going to be wait-listing people for a specific show this year.  Is it possible to create templates for "Waitlist - SHOWNAME"? i.e., 

Waitlist - Burlek Bordello
Waitlist - Star Bars!
Waitlist - The Main Event

If we can't get this done by Feb 4 or 5, there's not much point to it this year and I can kludge my way around it.

**Comment by bethlakshmi** [comment]
I can write code to do that... right now the per-show notification is only if you are accepted, cause that's what we scoped it to when I did the ticket.  But I don't think extending the logic is hard.

**Comment by bethlakshmi** [comment]
Deployed!
Also - I used https://www.burlesque-expo.com/email/list_template and made a template for each show
And updated the description at the top of the template to be accurate 

OF NOTE:  there is no role marker in the waitlisted acts (ie, no "casting") - so an act is not waitlisted for Main Event Compete or Main Event Not-compete - that would be a much bigger change.  It's just waitlisted for Main Event and in fact it's casting in the system is "Wait Listed".

**Comment by burlexpo** [comment]
_"there is no role marker in the waitlisted acts (ie, no "casting")"_

OK.  I can do a user-side work around.  -- Send all the Competition Waitlists, change the text, send all the non-comp waitlists.

**Comment by bethlakshmi** [comment]
Yeah.  We don't have a sane way to store this for Waitlisted acts - We use
the "casting" to mean "wait listed' and then I key off of that in a bunch
of places to screen out waitlisted acts from other displays.  I could
probably redo the logic, but not quickly.

-Beth
