### ISSUE TITLE
Paid Bid State is Confusing

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#39]
If I'm a vendor, it's really hard to tell the state of my application from the info presented on my personal homepage.  Can we put a big flag or something which says "You have not yet submiited your vendor application" if they have a draft vendor application?

**Comment by bethlakshmi** [comment]
Vendor only?  Or acts too?  It's the same lack of helpfullness.  How about:

- make an icon that it is like a big red "!" in a circle or something like that (something from font awesome)
- make the draft text in red & bold
- when you hover it works like a help text - and says something helpful ("you have not yet completed your application, please click here and submit your draft and/or pay your fee")

Also - do you want:
- big obvious note at the top of vendor edit that says "this is still a draft - press "submit" below to complete your application".
- Any sort of a note that they have paid/not paid (at least according to our system) - anywhere - on the main page, on the edit page, etc.  - I can tell if they have a spare, paid fee entry, and say "hey, you are all paid, just finalize this!!!"

**Comment by burlexpo** [comment]
Yes.  All of those things would be great.

**Comment by burlexpo** [comment]
I've got to admit, I'm confused.

The message below the act name says "This act is complete and can be submitted whenever you like. Review and Submit Now" which indicates (to me) that they don't need to do anything else (like pay an application fee).  

And I thought we were going to put in some sort of icon to help clarify what needs attention.  Maybe bids that are submitted get a big checkmark (.icon-check) in front of them and issues that need attention get an arrow pointing at them (.icon-arrow-right-circle)? 

Last, can we add a black line between "Review and Submit now" and "Propose another act"? Or, better yet, can we make "Propose Another act" a button?

<img width="724" alt="Bid Clarification" src="https://user-images.githubusercontent.com/5369404/71697532-44b80680-2d86-11ea-9d37-907b625c99aa.png">

**Comment by bethlakshmi** [comment]
Because checking off to-do lists is GREAT:

- [ ] make a button for new proposals, not a link, black color
- [ ] make red text, not red shadow
- [ ] make icons - checkmark for done, red arrow for needs work (any form of draft)
- [ ] remove "this act is complete.... " whole line is redundant.
