### ISSUE TITLE
special event links

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#394]
Reminder - the Events --> Special Events section has hard coded dates.  They are still hardcoded to 2021 - I'm not quite sure what you want to do - because there aren't Special events every day yet.

So this is just a reminder to review that section and fix links.

**Comment by burlexpo** [comment]
Help! I went and edited the dates -- just URL direct in the one line in the "Advanced" settings  -- and first some of them worked and now none of them do and I don't know how to fix it.

**Comment by burlexpo** [comment]
Ok-- so for some reason even though the old pages used a partial path as a re-direct, I had to use the full URL.  But it's working so... closed.

**Comment by bethlakshmi** [comment]
That's weird... I just went through and changed them to partial path and
it's working for me...
