### ISSUE TITLE
Other ways to view volunteer opportunites?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#400]
Unless I'm out of my mind (possible), there only seems to be one way to look at the Volunteer Opportunities,and that's on the big schedule.

Would it be possible to create a search box that would show me any instance of that word (maybe just in the volunteer title?) not dependent on day? i.e., if I search for "Follow" the results returned include every follow spot opportunity.

Or is it possible to just get a text list of the volunteer opportunities by Area (sound, light, etc)?

To have value, this would need to be done pretty soon...

**Comment by bethlakshmi** [comment]
Do you want that in a public view format?  How does the data get presented when you've searched for it?

For regular users wanting to see volunteers, we have:

- Volunteer signup page - https://www.burlesque-expo.com/scheduling/volunteer_signup - day by day
- Regular calendar view - https://www.burlesque-expo.com/calendar/Volunteer - also day by day
- List of all slots - https://www.burlesque-expo.com/scheduling/view_list/Volunteer/ - ALL slots marked as volunteer positions, conference by conference - this view is searchable by browser search... but it's a long list.

All of these options offer a checkbox that lets the user volunteer for stuff and pushes them through or system correctly (ie, signup or go to approval queue, send email, etc, etc).

My calendar views have always been day by day - I never did any of the layouts where you try to show the time things occur in a multi day view - for example, like a wall calendar with a square for each day.  

If you want something searchable, the really easy thing would be to make a new view that is a table (like our bid review tables, or the scheduling table I just revised), that comes with a search by default.  The search can cover anything on the page (date filtering might be a bit rough), or we can exclude stuff if we want to.  So it could search title & description if we want that.

That's easy - as in could do in < 1 week.  It's not "hey look I did it over lunch by accident" easy... but it's pretty fast.

A few questions, though:
- would the table include volunteer positions that are full?
- would we show both title & description? (some of these descriptions are empty/strange)
- What other columns do we show - title, description, staff area, parent event, time, day and a column for volunteering?
- sort initially by start day/time, right?  but let it be sortable by the user, too? (no effort needed by me)
- would I offer the "toggle column" feature?  


Alternate ideas:
- add a search to the list view 
- add a search to one of the calendar views

Either of these means me figuring out how to implement searching.  There's 2 options:
- do it in the browser (that's how the table views do it) - much better response time for the user.  Only a problem if there's so much data that you can't load it all at once (that's not our problem). 
- do it in the server - slower response time, but the only viable way for large data sets.

Either way, I'm a novice to implementing searching.  Surely there's good patterns I can steal, but it would be less reliably fast.

**Comment by burlexpo** [comment]
Ah-ha! Those views are pretty sexy... so this may not be a "create new tech" issue but a "get the info to the user" issue.  I'm a pretty savvy site user and I didn't know those views existed.  More importantly, I have no idea how to get to them even if they do.  More more importantly, when you click the "Volunteer" button on your dashboard, you're taken to the calendar view (which, for this user, is probably the least useful of them all).

1 - why do we essentially have two calendar views? Personally I think https://www.burlesque-expo.com/scheduling/volunteer_signup is kind of clunky looking.  I like the look of  https://www.burlesque-expo.com/calendar/Volunteer

2 - The list of all volunteer slots seems to load pretty quickly.

The easy solution might be to put a button at the top of each of the (three) views linking them to the other two types of views.  

For me as a potential volunteer, I think I'd like to know what the general categories of volunteer are (Staff Areas) and then be able to drill down on those -- something like going to the "All list" and having a list of staff areas at the top of the page which act as toggles (so I could see all the Lighting shifts and all the Stage Crew shifts, but everything else is hidden).

**Comment by bethlakshmi** [comment]
FYI - put it up on the test site:

https://burlesque-expo-stage.us.aldryn.io/scheduling/view_list/Volunteer/

PR waiting for a day or two for me to look at it with a clear eye

**Comment by bethlakshmi** [comment]
deploying this now
