### ISSUE TITLE
Email still broken

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#41]
...but in a different way.

I just went to send email to basically everyone on our list and when I clicked "submit" I got

Forbidden (403)
CSRF verification failed. Request aborted.
More information is available with DEBUG=True.

**Comment by bethlakshmi** [comment]
CSRF is the tool used for login.
Can you log out, refresh, and log back in?

I just tried using the website to send email only to you and I and I didn't hit this problem.
There's been no code change that should cause this problem.
