### ISSUE TITLE
Ticket Display on Dashboard

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#412]
This is incredibly minor, but currently all of the tickets/fees that a person has are displayed on a single line on their dashboard; i.e. "Act Comp - 1    Application Donation - 1    Whole Shebang - 1"

Could they instead be displayed:

Act Comp - 1    
Application Donation - 1    
Whole Shebang - 1

**Comment by bethlakshmi** [comment]
Can you give it another look? I think I fixed this with #408 - but I can't quite tell if we crossed in the mail.
