### ISSUE TITLE
Ticketing Reports part II

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#416]
There are 150 seats at the venue.  That is the maximum number of Whole Shebangs we can sell, because each passholder is entitled to a seat.

Performers are entitled to seats at the shows.  That means the number of Whole Shebangs we can sell is 150 - # of performers.

However, many performers will upgrade to a Whole Shebang, in which case the number of available weekend passes doesn't change.  Any given performer is already guaranteed a seat.  When they upgrade, they don't get more seats, they just get access to the classes, special events, etc.

Any time someone purchases an individual ticket to a show, we need to reduce the number of Whole Shebangs by that number of tickets.  i.e., John Smith buys 2 tickets to Star Bras!, we now have two fewer Whole Shebangs we can sell.

However, if John Smith buys 1 ticket to Star Bras! and 1 ticket to The Main Event, we only reduce the number of Whole Shebangs by one.  John is going to be sitting in the same seat (effectively) both nights.

The two cases with John Smith only apply to shows.  If John buys a ticket to a Special Event, we don't care.  Those aren't capped or if they are, we are asking people who have a Whole Shebang to make a reservation.

Last, I've created a "Staff Comp" that Marek is using to give people like you, me, John B, Mr Bergman, etc. Whole Shebangs.  Those people aren't likely to be using a seat at any given show, so they don't count in our total.

That means the number of available Whole Shebangs is: 150 - # of performers + # of performers that have upgraded - the number of unique individual ticket holders - the number of Socialites sold - # of Whole Shebangs sold + # of staff Whole Shebangs

I can probably do this by hand (or ask Marek to) but it seems like this is something a computer would be good at.

**Comment by bethlakshmi** [comment]
I've got a draft of the rough layout going now:

https://burlesque-expo-stage.us.aldryn.io/reports/occupancy/

And I'm starting to generate questions/thoughts:

1 - room capacity vs. overbook size - we randomly set up these data points a million years ago.  Do both of these matter?  if not, can I remove overbook size?  If they do matter - how do I calculate seats remaining?  Right now, I'm just subtracting from room capacity.

2 - how to track ticket sales that don't count?  We've got at least 2 - tickets sold as performer discounts, and tickets given to staff.  I don't want to hardcode this - that's too fragile.  Should I made a ticket level switch that you can check that says "does not apply to occupancy count?" or something like that?

3 - do you want a finer granularity on "linked tickets" vs. Whole Shebang?  Right now Linked Tickets are both Socialite & direct ticket sales like "Main Event", while Whole Shebang is listed out explicitly.  Could link all types of tickets that way?

4 - am I missing anything?

**Comment by bethlakshmi** [comment]
I'm going to close this with a won't fix.
Not only was the logic tricky, but we are now addressing this with Humanitix.
