### ISSUE TITLE
How to use "NEWS"?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#418]
The first column on the dashboard reads "News".  I said there was no way for me to put anything there and you said you were pretty sure there was.  I've poked around but I can't find anything.  Can you either

* create me some documentation so I can learn to use this feature OR
*  create a way for me to type something into a text editor and have it show up on everyone's newsfeed?

**Comment by bethlakshmi** [comment]
https://www.burlesque-expo.com/admin/gbe/usermessage/162/change/?_changelist_filters=view%3DLandingPageView

Is the location.

I can write docs for how to use these... but I'm not sure my docs will actually help.  Should I put something in the wiki?

The docs are faster, but making a text editor for this is doable - it's medium-size.

Let me know if doing that ranks over the occupancy report in #416

**Comment by burlexpo** [comment]
Having that message be HTML would be amazing - this is more important than the Occupancy Report

Having that message be editable by a non-admin would be great.

Currently, if you put any message in that colum, the header "NEWS" disappears.

**Comment by bethlakshmi** [comment]
What users do you want to be allowed to do this?   Any of our privileged users?

> Currently, if you put any message in that colum, the header "NEWS" disappears.

Not sure what you mean - this is what I see:

![Screen Shot 2023-03-29 at 10 02 22 AM](https://user-images.githubusercontent.com/4542707/228563488-73595722-e907-4269-8250-685d5253a46d.png)

**Comment by bethlakshmi** [comment]
You may be a victim of caching?  I cache the user's dashboard on a per-user basis, and I do so pretty aggressively. 

There's a LOT of data that gets pulled to build this page, which means for a busy person, the response time can be among our slowest times.  And it's the return page for a bunch of normal user flows (bidding, act tech, etc), which means users have a bad experience if I don't.

**Comment by burlexpo** [comment]
1) If you can send out emails, you can put a message in the News column

2) There used to be a column-header in  Vast Shadow (the same style as "Betty Blazie's Stuff") which read "News".  Now there's not.  There's just this line item hanging out by itself.

**Comment by burlexpo** [comment]
> You may be a victim of caching? I cache the user's dashboard on a per-user basis, and I do so pretty aggressively.
> 
> There's a LOT of data that gets pulled to build this page, which means for a busy person, the response time can be among our slowest times. And it's the return page for a bunch of normal user flows (bidding, act tech, etc), which means users have a bad experience if I don't.

No, I see the same thing you do.  I just mean the header "News" has disappeared from the top of the column

**Comment by bethlakshmi** [comment]
That's been gone for 2 years or more?  The last time this part of the code
changed was Jun 2021.

It does say "News" if you are in a mobile sized view... that's part the
tabs that don't look like tabs.

If it ever said "News" in a desktop view, I can't see it in the code...
glad to put that in there?  I could do a thing that is "if there is content
-- put a header that says "News" " - otherwise leave blank.

Long, long ago - this area used to be HTML editable, because I had the
ability to have a Django CMS plugin that would let me use it for partial
page content - so you could HTML edit text or any other CMS-y thing there,
and Django CMS would render it for me.  That feature was removed from
Django CMS a while back.  I think I pulled it in either 2021 or before,
because the documentation said the feature was no longer available.

-Betty

**Comment by burlexpo** [comment]
My memory isn't perfect, but I'm pretty sure it said "News" this morning when I looked at it.

Regardless. it would be nice if there was a header on that column that said "News" or "Announcements" and if I (and others) were able to add formatted text to that space.

**Comment by bethlakshmi** [comment]
Can do.

**Comment by bethlakshmi** [comment]
OK, based on our talk last night, what you really want is #242 - which you are right, I never implemented because I ran into all sorts of walls on it.

I'm gonna make another look to see if anything has gotten better from last time.

If nothing works, I will write something very bare bones.  Minimum features would be:
- available to anyone who sends email in our system.  All users can edit each other's content
- can show up on the left side of the dashboard (now), and on the home page (someday, later ticket)
- has a header and a subject, date of posting and who posted it
- sort the feed by date newest to oldet
- let the user pick 2 dates - a date to post it, and a date to take it down.  
- ability to edit a draft or hide a post without destroying it completely - could be done via date controls

I'll end up doing what ever I think is fastest/easiest in terms of posting/hiding and the date controls. 

Anything else?

**Comment by burlexpo** [comment]
Bare bones HTML functionality (at a minimum).  I don't need to be able to insert images or tables, but things like bold, italic, and underline; a couple of layers of header; ordered and unordered lists; and links would all be really useful.

**Comment by burlexpo** [comment]
Some potentially useful links
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog
https://blog.logrocket.com/use-django-rest-framework-to-build-a-blog/ (do we use REST?)
https://djangopackages.org/packages/p/wagtail/ - Wagtail.  Maybe more powerful than we want, but updated frequently
https://djangopackages.org/packages/p/django-bona-blog/ -- looks like a basic Blog with the feature set we want

**Comment by bethlakshmi** [comment]
Yeah I just looked through a bunch of the stuff listed here:

- the first two are different sets of instructions on how to build your own blog, as a learning tool for learning various things.  Blogs are really, really common "just meaty enough to be educational" projects.  Which makes them great learning tools, and it's one of the reasons I'm wiling to just write my own.
- Wagtail is it's own CMS - it's going to cause a bunch of confusion w/ respect to Django CMS
- Bona Blog - creates another dashboard, no instructions for embedding on a page, this thing expects to be running all by itself as a separate site.  That's a problem with a lot of these - no embed-ability

And no - we don't use REST - it's a common tool for having a thick front end -- and that's something I've been dancing around doing, but that moves this project from "medium" to "huge"

I think I'm going to do:

https://github.com/dmptrluke/django-published

and just write the rest of it.  This module gives me clean functionality for the publication date controls, and the rest isn't too hard.  By only including a low level tool, I will then be able to write the display stuff, which is where we need something pretty custom.

**Comment by burlexpo** [comment]
Django-published looks good

**Comment by bethlakshmi** [comment]
How do we want navigation to work?
Easiest is special menu - I can let privileged users use that to manage the list of news articles and edit/create/delete.

Looking at it - we could put the item in either "Manage" or "Contact" -- any preference?

**Comment by bethlakshmi** [comment]
@burlexpo - Great news - I've got the first draft of the complete feature done.

I just put it on the test site:  https://burlesque-expo-stage.us.aldryn.io/main/

### Features:

- on Special --> Contact - there is a new entry "News Articles"
- that gets you to a management screen that is available to anyone who can email roles, bidders, or individuals.
- on that screen you can add, edit, view, or delete articles.  Part of editing is deciding when they can be published.  View shows you what readers see, but if the post is not public yet, there's a warning banner to make that clear.
- it automatically attaches the person creating it as the author - author can be changed in the admin but not by regular users
- the [landing page](https://burlesque-expo-stage.us.aldryn.io/gbe) shows all users the published articles on the left hand sidebar
- I built a [URL](https://burlesque-expo-stage.us.aldryn.io/news/list) (not linked anywhere) for showing a public view of news articles.  
- There's an admin side - GBE -> Articles

### To Do:
- write a plugin so you can use it on the main page, too.
- set up more HTML edit fields - right now, it's the limited set we give to class bid/act bid/performer bios - I think it would be better to use the advanced set we give for email editing.
- lots of tests to be written

### Questions:

- anything I should change in terms of the public list or the public article details?
- should I limit the # of articles shown?  Right now it's infinite, capping them to a number would be easy
- is it worth it to have a separate page listing the news articles?  If not, easy to delete
- anything else you think we need in terms of the privileged user management side?

**Comment by bethlakshmi** [comment]
Just changed Special --> Contact menu item to Special --> Manage

For the record - I have no copy of an email or ticket saying you wanted to do the Special --> Manage menu. The last info from you on this is that django published looked good.

**Comment by burlexpo** [comment]
_anything I should change in terms of the public list or the public article _details?_

Can we increase the font size of the headline/article name just a smidge, and put a line break between the title and the date? Also, de-bold the date but maybe italicize it

_should I limit the # of articles shown? Right now it's infinite, capping them to a number would be easy_
Are we showing summaries on the front page or the entire article? Ideally, we just show the first few lines in the NEWS column and the click for the full article

The answer to this decides how many articles I want to show

_is it worth it to have a separate page listing the news articles? If not, easy to delete_
Yes, very worth it

_anything else you think we need in terms of the privileged user management side?_

I just want to make sure that I can write a bunch of articles when I have time and schedule them to go up (or come down) in the future.

**Comment by bethlakshmi** [comment]
- tweaked the look of the list per comments.  Removed the bullets, too.
- limit of 4 enforced
- yes - it's a summary field
- yes, you can time the delivery.  
updates posted

**Comment by bethlakshmi** [comment]
Got in the striped rows.
And it sorts by published date or most recent update date
Testing is done.

This is big, so the pr will probably take me 3-5 days.

**Comment by burlexpo** [comment]
@bethlakshmi  - The articles are displayed with the oldest article on the top.  Can we reverse the order (so the newest is closest to the top)?

**Comment by burlexpo** [comment]
_And it sorts by published date or most recent update date_

Which means there's no way to backdate an article, right?

**Comment by bethlakshmi** [comment]
Publishing right now!!!! 🥳 🎉 

Also wrote docs for it:  https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/wiki/News-Articles
