### ISSUE TITLE
Make copies of all sent email msgs available

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#419]
RIght now, only email sent through templates is stored as text on the server.

Either

1 - make it so I can rever HTML versions of email (1st choice)
2- store all email messages as text someplace I can recover them

**Comment by bethlakshmi** [comment]
Wohooohoooo!!

I just got django-post-office to update.  That was far easier than I feared!!

And the updated version fixes the bug in admin causing this problem.

I'm deploying to test so you can see for yourself, and will push in the freshest data there, so you have an instant access to HTML emails you've sent on the live site.  I'm retesting all our flows just to be safe, and will publish fix in a few days to live.

**Comment by bethlakshmi** [comment]
https://burlesque-expo-stage.us.aldryn.io/admin/post_office/email/

update of code is done, data is coming in in a min or two.

**Comment by burlexpo** [comment]
Tested it and  yes I can see HTML messages.

I also got copies of the email I sent through the test site, which I thought wasn't supposed to happen (I thought any email sent through the test site, no matter to whom it was addressed, only went to you, @bethlakshmi )

**Comment by bethlakshmi** [comment]
Cool.  Pushed it to live site after peer review.
Checked the code - on test it goes to the admins - that's me and you (info@....)
