### ISSUE TITLE
Teacher > Class relationship is screwed up somewhere

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#420]
If I go and view the Class Descriptions (https://www.burlesque-expo.com/scheduling/view_list/Class/)

It shows every class as being taught by every teacher...

![Screenshot 2023-03-31 at 10 38 38 AM](https://user-images.githubusercontent.com/5369404/229152211-851bab29-48d1-44df-a3fc-3425d0b11139.png)

**Comment by bethlakshmi** [comment]
Hot fixing right now.
It deserves a test, so not closing until I do it right

**Comment by bethlakshmi** [comment]
tune ups being deployed now
