### ISSUE TITLE
Too many Volunteer Notifications

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#423]
Currently, every time any volunteer adds or drops a shift, Scratch gets email.  Which is turning into a lot.

_Quickie_ - stop sending Volunteer Change notifications that don't need approvals to everyone.  Just send ones that need approval (to everyone)

_Longer_? Send **all** Volunteer notifications but only to the Staff Lead for the related area

**Comment by bethlakshmi** [comment]
Yes - quickie version is quick

Also the longer version is fast enough... question on that, though.  It's possible for a volunteer position to be created outside of a staff area.  For example Go-go dancers for shows, or the Swap Meet.  In those cases should it?
A - send no email to any staff
B - send to volunteer coordinator

Was aiming at B for safety?

**Comment by bethlakshmi** [comment]
Also - does the same logic apply on Withdraw - ie, if a volunteer withdraws from a shift that doesn't need approval - are we sending an email?
