### ISSUE TITLE
Tweak layout for shows

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#424]
Right now the space between the top of the Name Label and the bottom of the picture above it seem to be the same and at first glance it's hard to tell which photo the label belongs with.

Can we slightly increase the size between the rows? Or decrease the space between the label and the photo?
![Screenshot 2023-04-06 at 10 16 35 AM](https://user-images.githubusercontent.com/5369404/230406116-14894258-73e6-4aff-bf8d-3a439482667d.png)

**Comment by bethlakshmi** [comment]
Two options:

Dark Grey boxes
![Screen Shot 2023-04-07 at 4 28 38 PM](https://user-images.githubusercontent.com/4542707/230674740-1265ad81-3750-4bcb-a16e-3433c5e133e0.png)

more space separating the words
![Screen Shot 2023-04-07 at 4 22 55 PM](https://user-images.githubusercontent.com/4542707/230674742-1c7f4129-2588-4064-8e2c-235896c63a20.png)

Personally I like the boxes

**Comment by burlexpo** [comment]
I think the boxes look busy.  Let's go with more space.  Or ask Luna.

**Comment by bethlakshmi** [comment]
Don't care too much - I'll do the more space
