### ISSUE TITLE
Add link to Video to Act Tech info

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#435]
Please add the link to video information from the Act Submission to the related Act Tech report (see image)
![Screenshot 2023-04-25 at 11 50 05 PM](https://user-images.githubusercontent.com/5369404/234465748-ec8f12eb-1b6d-474c-8fd7-166829d8c56c.png)

**Comment by bethlakshmi** [comment]
for the record, it's already on the table that leads to this page:

![Screen Shot 2023-04-26 at 11 14 36 PM](https://user-images.githubusercontent.com/4542707/234750505-b28baa84-32c0-44cc-b0b8-24d458e77ea6.png)

But it's easy enough to put it here too, so glad to do it fast.

**Comment by bethlakshmi** [comment]
deploying now
