### ISSUE TITLE
Stage Managers and Hosts need access to view tech info for shows

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#446]
And assigning someone the role of Stage Manger doesn't seem to do that

**Comment by bethlakshmi** [comment]
Who did you assign.  It should and I could potentially debug if time allows
this afternoon.

**Comment by burlexpo** [comment]
Mina. Except when I view her page she has the buttons so it may be a caching issue--Team BurlExoBurlesque-Expo.com#BurlExpoOn May 3, 2023, at 10:31 AM, bethlakshmi ***@***.***> wrote:﻿
Who did you assign.  It should and I could potentially debug if time allows
this afternoon.
