### ISSUE TITLE
Troupe members don't get rehearsal on daily schedule

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#451]
It's on the conference welcome letter, but not the daily email.

**Comment by bethlakshmi** [comment]
It's more than rehearsal - they don't get the show either.  Quick fix is being tested, and hope to deploy before Saturday emails go out.

**Comment by bethlakshmi** [comment]
Also - look into why some performers are able to be "interested" in a rehearsal - as Deb Kavis's Schedule shows - I didn't think rehearsals were public, or able to be attached to a person's schedule this way - they are more or less secret unless one picks it through act tech info.

**Comment by bethlakshmi** [comment]
Should a contact get troupe show & rehearsal on a daily schedule?  In our case - Eva - who was planned to be not at the expo - really didn't need it on her schedule... right?  She's the contact, but not a member of the troupe.

**Comment by burlexpo** [comment]
I think Eva’s situation was unusual. I think 99% of the time, the contact will be performing with the troupe

**Comment by bethlakshmi** [comment]
Fixed this with the big people migration a few weeks back
