### ISSUE TITLE
Hide tickets when sold out or no longer on sale

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#455]
If you go to https://www.burlesque-expo.com/ticketing/ all of the past tickets for this year are on the site (as well as the ticket for next year).  And I can't figure out how to hide all of an event.  I know I can hide individual tickets.

Ideally, events that have no tickets that are currently on sale (by calendar) should not appear on the site at all

Events that have active tickets, but all active tickets are sold out, should have a "Sold Out" banner

**Comment by bethlakshmi** [comment]
I built this into the Humanitix ticket display.   If we ever go back to Eventbrite or BPT, the issue will come back, because the filters for those are quite different.  But closeable for now.
