### ISSUE TITLE
Change Rehearsal Timing

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#458]
Rehearsals should be in 15-minute blocks with the potential to schedule 2 people per block, rather than 1-hour blocks with 8 performers per block.

**Comment by bethlakshmi** [comment]
I think the only coding change would be that we can only book in 1/2 hour increments, we don't offer times like 1:15, 1:45, etc and we require that the min time is half an hour.  I can go down to 15 min -- but it'll offer that to all event types.

The rest is a configuration choice when we are scheduling.

**Comment by burlexpo** [comment]
Question: Currently when scheduling an event, one puts in the start time (i.e., 2:00 p.m.) and then puts in the duration, expressed as a decimal of hours (i.e., 1.5).  Is there a reason why we just don't put in the start time and the end time?
