### ISSUE TITLE
Move the NEWS feed to the front page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#472]
We created this cool "Article" function which appears on Dashboards -- which is great if you have an account and are logged in... but can we have the newsfeed appear on the Main page (with the countdown)? https://www.burlesque-expo.com/main/

**Comment by bethlakshmi** [comment]
We have a plugin for that - you can put it whereever you like:
![Screen Shot 2023-06-14 at 5 45 06 PM](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/ec5eb376-fb6f-46bd-86dc-84721252ba21)

- Edit the page, 
- open the sidebar
- choose the + in whatever section you want to add it.
- it's under the GBE Plugins section

Once you pick it, you can set how many article summaries show up.

**Comment by burlexpo** [comment]
By Jingo you're right! So I did.
