### ISSUE TITLE
Fixed Menu only Fixed when logged out

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#477]
Works fine when I'm not logged in.

When I'm logged into the site, the menu is **not** fixed.

**Comment by bethlakshmi** [comment]
I can't replicate this:

![Screen Shot 2023-06-22 at 11 50 30 AM](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/18f85b17-45cc-41da-ac30-2f7955eae055)

Can you double check your URL just in case you found a path back to the main site?

**Comment by burlexpo** [comment]
URL seems to be the same as yours

https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/293691be-3daa-4410-8f48-153e3ff17664

**Comment by bethlakshmi** [comment]
We talked - it's good enough
