### ISSUE TITLE
[Website] Look and Feel changes

### ISSUE THREAD

**Issue by carynaudenried** [bethlakshmi/gbe-divio-djangocms-python2.7#493]
**Design needs**
- New background image
- New hero image for homepage
- Fonts, colors, styles

**Notes from emails with Scratch and Betty**
- Use our current logos
- Use current "witch" illustrations somehow; slightly spooky/dark theme will work well. _Possibly incorporate witch illustrations into a background image?_
- Possibly look in to a large hero image for home page using poster art for next year's event
- Luna's thoughts: We could also lean slightly in to an art deco theme based on the look and feel of the current (circle) logo

**Comment by burlexpo** [comment]
1) I like art deco a lot... although I'm not sure how well it plays with the "cartoony" witches.

2) I had discussed using the witches as part of the headers or callouts and I meant something like this 
![News](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/cb30ac4f-7eb1-4af6-b80a-39592d01e086)

**Comment by carynaudenried** [comment]
@burlexpo Alright coming back to this one!

Here's a bunch of directions we could go for the background and homepage image. Let me know if any of them resonate with you! For the first three (purple backgrounds), I created the background image from the witch illustrations, so I can adjust anything about the color or brightness.

Call out anything you like or don't like and we can combine the elements that work best. I didn't do anything with the actual homepage content below the banner on these, we can work on that afterwards.

![03_GBE_Home_SKETCH_desktop](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/4b2908d7-b2ff-45e6-9aa0-a3a01142038b)
![04_GBE_Home_SKETCH_desktop](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/aa0dad6b-015e-4381-b207-2d8ba837e7d4)
![05_GBE_Home_SKETCH_desktop](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/efceb134-6de6-445a-83ad-a61f1f8e90d6)

![01_GBE_Home_SKETCH_desktop](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/8dab2c91-ace0-4842-be56-83c9f67219b0)
![02_GBE_Home_SKETCH_desktop](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/bac9523e-5d06-408f-bab9-626b522cc0e9)

**Comment by burlexpo** [comment]
@carynaudenried !!!! These are _amazing_! Thank you for making my choices so hard... but I think I like the first one best (https://user-images.githubusercontent.com/112599862/267800463-4b2908d7-b2ff-45e6-9aa0-a3a01142038b.jpg).  I love the witch wallpaper!

@bethlakshmi can we make this happen?

**Comment by bethlakshmi** [comment]
Yes, I think I can make 90% of it happen with no code.

I need:
 - the image of the spiffy wallpaper witches.
 - the image of the banner with the transparent background and the pumpkin boobs, convention moon and dates in the foreground.
 - to do a tiny little bit of code to make the banner flush to the content panel (we have a margin right now)

The coding can be totally separate from the art updates.  The art updates can be done to the live site now with no code changes.

A couple of questions:
- are there any changes to colors/sizing of the content panel? Or the fonts?  - FYI, I built a little panel/font previewer for all the variants on the site:  https://www.burlesque-expo.com/themes/style_edit/3 - see "Panels" and "Text" - I figured that if we ended up changing the background of the main panel, we probably also wanted to change the background of the variants.  
- I assume I should keep it so the width of the banner is flush with the content panel, so they both resize together.
- Is anything different on mobile?

I could definitely do this in stages:
1 - update images 
2 - fix the code for the banner margin
3 - do any updates of panels/texts

FYI - it's easiest for me to work in RGBA - it's certainly easy to convert from HEX, no problem, but don't convert to HEX on my account. :) I pretty much defaulted to RGBA on the site cause I found a nifty color picker for it.

**Comment by carynaudenried** [comment]
Nice! Ok I can get you these tomorrow while I wait out the storm!

**Comment by carynaudenried** [comment]
Ok attaching images here!

**Background image** 
I made a 1920 x 1080 jpg. Questions for @bethlakshmi 
- Is there a different size you prefer? Do you need a 2x version?
- For mobile would it be helpful to have a separate portrait-format background image?

![BG_Witches](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/c54447d7-2049-4070-b939-8b757404e2ba)

**Hero banner**
I included 1x and 2x versions of both a desktop and mweb version. Again, use what you need/what seems to work best.
![Hero1_Mweb](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/efcebe5c-92e6-42bc-9c75-2e36758608e1)
![Hero1_Mweb@2x](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/1adda9ac-4c8c-449d-9b54-6a9bda7ad86a)
![Hero1](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/d45b0b9e-cd31-41d0-89b8-7bb48e0c3d87)
![Hero1@2x](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/dd675588-a32a-49eb-8f13-651d7ea4cccd)

**Questions**

are there any changes to colors/sizing of the content panel? Or the fonts? 
- I kept the width of the content panel the same for these. I don't see a need to change this. For the fonts, I was thinking we'd move to Montserrat for the body text and the subtitles. I still want to get you more detail on the designs for these content panels, but this would be a good place to start.

I assume I should keep it so the width of the banner is flush with the content panel, so they both resize together.
- Yes, that sounds good! If the sizing of the banner image is a bit off, I would just center it and make sure it stays centered as you resize. It should be pretty forgiving since the edges are transparent so I'm open to whatever implementation makes most sense.

Is anything different on mobile?
- I was thinking we should use a different hero banner image, since the desktop one is quite long. Is that something you can do? I supplied an "mweb" version of the banner above where I condensed the design a bit. The idea would be to have something like this for mobile:
![image](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/112599862/9e467daa-52ee-4762-a52c-1eb78f109379)

**Next steps**
Next I'm going to look at some key pages and work on creating image headers with the witches to add some extra personality, like Scratch suggested above. @burlexpo do you have any pages in mind you'd definitely want to have interesting image headers for? I'm thinking:
- Shows (show the same header for all Show pages? so you don't have to create a new banner every time you add a show or adjust the names)
- Shopping & Events (same, show the same header for all pages under this theme)
- Your Expo
- News
- Volunteer

**Comment by bethlakshmi** [comment]
OK, put a first try of updates into staging:

https://burlesque-expo-stage.us.aldryn.io/gbe?edit

Since this is a publicly accessible URL, we can also hit it with our phones.  Download timing will be a bit off, since staging isn't cached the same way, but the delivery quality will be the same.

It includes:
- the wallpaper
- the biggest hero banner
- changes to pull the banner's padding and margin to zero.

My thoughts:
- on desktop, the banner feels blurry to me - is there a way to do a crisper one?
- on mobile the banner looks pretty good - I think Django CMS has a image responsiveness thingy that happens under the covers?
- the image on the wall paper looks great on desktop, and is hard to see on mobile, just because there's not a lot of real estate to see.  

I could figure out how to do a responsive wallpaper pretty easily.  Mobile banner will probably take more messing around, since its mostly happening in the CMS system, so I have to see what they'll give me.  What do we think?

Also, I noticed the main page content columns are pretty awful on mobile - @burlexpo - mind if I fix that on the main site?  My thought would be to have the news appear first, and the code of conduct below them.  I can set what you have so that it works one way on mobile and another on desktop.  I put up a demo of what I suggest on staging.

**Comment by carynaudenried** [comment]
Hey! So I just checked this out. It looks like the desktop site is pulling the mweb banner size, which is stretching it and making it blurry. The desktop version is wider and shorter, and has the date/location text hanging out on the right side. 

I think it'd be worth trying to have the site pull a different banner for desktop and mobile breakpoints - but if you can't, I would err on the side of just using the desktop version.

**Comment by bethlakshmi** [comment]
OK, I may be getting lost in the banners on this git ticket?  I just tried the other biggest-byte-size banner (now up on staging) and it doesn't look much better.

When I downloaded the 4 banners I have:

Hero1 mweb - 287KB
Hero1 mweb - 968KB (I think I put this one up there...)
Hero1 - 308KB
Hero1 2x - 1MB

I just replaced the banner with Hero1 2x - https://burlesque-expo-stage.us.aldryn.io/gbe/?edit_off=true

And the alignment definitely looks better.  And the text "Salem MA, April 25-28, 2024" is nice and crisp, but the pumkin witch pinup is blurry.

After staring at these for a second round of staring, I now see it's obvious!  That the moon holds the dates for the mweb to allow for the narrower format. 

I also make my brain work and got it displaying responsively.  No code needed, although the banner setup is a bit less intuiative in Django now, it was pretty easy to set up.   Give it a whirl.  I used the 2X size for both.  I could go more granular of we want?  Bootstrap gives me tags for these sizes:



Breakpoint | Class infix | Dimensions
-- | -- | --
X-Small | None | <576px
Small | sm | ≥576px
Medium | md | ≥768px
Large | lg | ≥992px
Extra large | xl | ≥1200px
Extra extra large | xxl | ≥1400px

Right now I use:
- mweb 2x for x-small, and small 
- hero 2x for medium through extra-extra large

But could certainly break down to smaller sizes if we see a value.

**Comment by bethlakshmi** [comment]
@carynaudenried - I'm worried that the header picture on desktop size is still blurry - although I think I'm now using the right one?  I'm wondering if git hub smooshed it down?  Can you send me that one directly via gmail?

**Comment by carynaudenried** [comment]
@bethlakshmi Ok I'm sending one via gmail shortly! Looking at the images, I think I know what might be happening. The witch illustration isn't vector so it doesn't scale up smoothly and it's only so big. I'm going to size her down a bit so that the 2x image size doesn't exceed the size of the original art. 

Sounds good with the sizes you're using, I think they look good otherwise. I think most laptop screens and smartphones work better with 2x assets so it'd be worth using the larger sizes.

**Comment by bethlakshmi** [comment]
Got updated file and updated it on live.

Looking good to me.  Closing this ticket.  I think if we want to do more - let's do another one for fonts, colors, styles.
