### ISSUE TITLE
Set up ticket cron - after getting paid account

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#5]
Divio does have a way to do this:

http://support.divio.com/en/articles/19218-how-to-manage-cron-jobs

But I can't do it until after we pay for the service.

**Comment by bethlakshmi** [comment]
Pull request ready to reformat our old script as a much simpler BPT command.
Will merge when it proves that our live server (currently on this branch) is able to import a transaction successfully. 
Needs a transaction to get set up by @burlexpo so I can sync and watch it succeed.

**Comment by burlexpo** [comment]
@bethlakshmi I think I've added an application fee to your account.

**Comment by bethlakshmi** [comment]
![Uploading Screen Shot 2019-11-19 at 9.50.08 PM.png…]()

Working!  The first run showed a bit of data corruption in early times users (@burlexpo  and I).
That is now cleaned up on our live server, and thus this retest works perfectly!!! 
WhooHOOO!!!!!
