### ISSUE TITLE
No "Act Review List"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#511]
I logged in and went to https://www.burlesque-expo.com/act/reviewlist (using the _Special_ menu) and got a **Server 500** error.

**Comment by burlexpo** [comment]
@bethlakshmi is this ready to be closed?

**Comment by bethlakshmi** [comment]
Yeah - #512 is it's nerdier twin that will have actual code fixes.  Workaround for this is in place.
