### ISSUE TITLE
New menu structure questions

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#513]
I see the new menu items!  Great to have a facelift!

is there anything you need links for?  I see a few dead links here and there - for example Taste of Tease - we do have a link for Drop In classes:

https://www.burlesque-expo.com/scheduling/view_list/Drop-In/?conference=GBE2023 
(this is 2023's)

And it would not be hard at all to do a per-day URL, as well.  Or to have a day by day calendar just for these.

Similarly, we have a Special Event description list:

https://www.burlesque-expo.com/scheduling/view_list/Special?conference=GBE2023
(2023 version)

I don't have a special calendar - Special events are on "General" along with shows.

Also - with setting up the new 2024 conference and ending 2023 -- most of the dynamic pages load with very little info.  Want me to set up the links to go to 2023 for now?

**Comment by burlexpo** [comment]
All done.  Bye-bye.
