### ISSUE TITLE
What does this button do?  (show hotel booking info)

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#549]
<img width="839" alt="Screenshot 2023-11-15 at 2 57 51 PM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/e7e584f0-7d6e-47ea-86d9-29ad74288e1c">

In the code, this setting has no purpose.

What did we want it to do?  Do we even still want that?

I can't think of what info we'd want to put on someone's landing page relating to this that we'd want a separate control for.
If it was "I'm interested in hotel info" - let's just make it part of the checkboxes above and make it an email-able interest.
If it was "I want to see my hotel booking on the landing page" - oy, we are so far from that, it's crazy.  I doubt we'll ever do it, so let's remove the false suggestion that we do.

Thoughts? @burlexpo  - if this is really another way for them to show interest, let me refactor it while I work on #22

**Comment by burlexpo** [comment]
Kill it.  I think it's a holdover from Intercon formatting.

**Comment by bethlakshmi** [comment]
Die little data blob!!

**Comment by bethlakshmi** [comment]
Removed with #555
