### ISSUE TITLE
Remove "No Acts to Review" for non-reviewers

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#551]
Some of our users are easily confused 

Someone contacted me because they were sure they submitted an act, but on their "Stuff" column (where I told them to look) there was a line which said "No Acts to Review".  I took a look and sure enough... there it is.  It's intended for members of the Act Review committee, but if you're not a member of the ARC, you get a box that tells you you have no acts to review.  Hence the confusion....

![Screenshot 2023-11-20 at 10 44 05 AM](https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/5369404/fe4ad913-d517-4ff2-b5ce-f670226fb8ca)

**Comment by bethlakshmi** [comment]
Yeah, that's definitely a bug.
Probably I introduced it in doing the summary (you have X acts to review instead of long list of acts).

**Comment by bethlakshmi** [comment]
deploying fix now.
