### ISSUE TITLE
We're getting BBrrrrrlesque tickets.  Why?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#554]
https://www.burlesque-expo.com/ticketing/

**Comment by bethlakshmi** [comment]
I hid them from the public view, but they are still syncing:

https://www.burlesque-expo.com/ticketing/ticket_items/

I see that we DO have the organizer filter set on our end... so that only PBS events should be coming through.  But clearly Beautease events are coming through.  I'll research.

**Comment by burlexpo** [comment]
OK -- that may be my screw-up.  When I first created the event, I created it as though it were owned by PBS... and then when I realized the problem, I changed it.  So that may be the cause.

**Comment by bethlakshmi** [comment]
Cool, since we're not using EB anymore and we do have a filter that maybe even works, I'm closing this.
