### ISSUE TITLE
Act aplications should close more gracefully

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#568]
- break out applications open/close into each type of bid (on the conference)
- and detect if act/class applications are open/close on the user's dashboard and only show a button if it will let the user do the thing.
- hide volunteer button if there are no volunteer options to volunteer for (very low priority)

**Comment by bethlakshmi** [comment]
I got curious on the history of these buttons.  They came from #377 - because we wanted to move the buttons from the box in each bid area on the landing page, to be on top so they are super obvious.  We did it early 2023, so would have been doing as we were working on GBE 14.

So in a sense they always were on that page - but they used to be in the act/class/costume bid boxes.

**Comment by burlexpo** [comment]
@bethlakshmi -- this one just got ugent.  I realized it means we can't accept Vendor bids.  So that part, at least, needs to be carved out ASAP.

**Comment by bethlakshmi** [comment]
Ok.  Also last I knew, we had no payment setup for vendor bids.  So while I
do this, that can be set up

B

**Comment by bethlakshmi** [comment]
#571 - deploying now.
Planning to turn on Vendors, Classes, and Volunteers, and leave Acts and Costumes off (since we have no costume exhibit planned)
