### ISSUE TITLE
Some kind of warning on landing page?

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#569]
@burlexpo - sorry for this super vague ticket. but...

One day you and were driving and talking about the site, and you said you wanted some kind of warning for ???  that would show up in the same basic place/way as the "please do your act tech" warning.

I honestly forget what the warning condition was - I don't think it was even connected to act tech info or act submissions...?

If you do, please remind me.  If not, I'll probably delete this ticket in a week or two.

**Comment by burlexpo** [comment]
Replaced by #570
