### ISSUE TITLE
Act Review Metrics/Adjustments

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#575]
Two quick questions.  No idea if the answers are going to be quick.

1) Is there a way for me to edit someone else's Act Review scores? I don't mean for nefarious purposes, but -- for real example -- more than one person has not submitted an essay or a video, and Margo has not rated them in those areas or rated them N/A, where according to the rules, they ought to get 0.  Rather than sending Margo email and saying "hey, got edit this and this" and risking either a game of telephone or her not doing it, I was wondering if there's some place on the Admin screen I can just go and fix them

2) It would be nice but not essential for me to see at a glance how many people had reviewed each act.  So on the big Act Review page if it just gave a number in the column to the left of the first scores. That way I can see if someone is ready to be cast.

**Comment by bethlakshmi** [comment]
1 - not easily, but it's possible.  The link is:

https://burlesque-expo.us.aldryn.io/admin/gbe/flexibleevaluation/

There is 1 entry per category, per reviewer, per act.  And there's no filters.  But it's doable if you want to take long enough at it.

I could pretty easily add a few creature comforts here:
- a per reviewer filter to get just Margo's
- a per category filter to get just Video
- a bulk edit that would let you change the ranking

Which would speed up the task quite a bit.  Not hard if you want me to.

2 - Yeah I can do that.

I'm gonna do both, let me know ASAP if you don't want that.

**Comment by bethlakshmi** [comment]
How's this?
<img width="1205" alt="Screenshot 2024-01-23 at 8 37 47 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/f1aa3d34-d563-4342-ae8a-28c41f975306">

**Comment by burlexpo** [comment]
@bethlakshmi -- yup, just like that!

**Comment by bethlakshmi** [comment]
And like this
<img width="1096" alt="Screenshot 2024-01-23 at 8 45 43 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/c1ca136d-49ab-45d5-96a4-ab92ef78d337">

**Comment by burlexpo** [comment]
A filter by Conference would be great too, since there are something like 18000(?) entries in that database.

**Comment by bethlakshmi** [comment]
Good point, done.
Deploying this onto test.  I figured we could use fresh data - and if you wanted the review #'s ASAP, this would give it.
The PR is simple enough that I'm happy to pull it tomorrow.  But I am running the full test suite now, just in case, and want to give it 1 day.

**Comment by bethlakshmi** [comment]
deploying now

**Comment by burlexpo** [comment]
@bethlakshmi When I use the built-in Search bar in Admin, I get (I think) a Server 500 Error.  I say "I think" because the text is partially obscured by the admin bar.

**Comment by bethlakshmi** [comment]
Yep.  Me too...
Turns out I utterly utterly failed on the search configuration for this page.  Virtually everything (except syntax) that could have been wrong, was wrong.  Great case study on how NOT to peer review one's own work.  :(

Fixed now with hot patch to live.  Will finish deploying in < 10 min
