### ISSUE TITLE
Not all performers showing up on email filter?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#581]
I'm not sure if this is a question or a bug, but either way I need to figure it out quickly.  

Currently, The Main has only accepted the non-competes.  There are 13 of them, plus the MC.  If I go to manage the Main Event by clicking the button on my dashboard, and then click "Contact Performers", it only gives me 11 performers.  If I go and look at the show page, I can see 13 performers.

We're not emailing me (the MC) and we don't seem to be emailing Mistress Manifest, Moxie Blue, and Vix Versa.  I know Manifest got her acceptance, and looking at her profile, I can see she has both "Email me about my past and present proposals" and "email me about my past and present activities" turned off.  Which I think is keeping her from getting mass emails to current performers.

Nope.  i thought I had it figured out, but Vix Versa has those boxes checked and she also doesn't show up in the filter.

**Comment by burlexpo** [comment]
@bethlakshmi I'm pushing this little mystery to your attention again...

**Comment by bethlakshmi** [comment]
Moxie Blue & Mistress Manifest - have bidding and participation emails turned off
Vix Versa = Nicolette Rue and shows up as a bidder email
And mailing to Act Bidders DOES email to you

Checking the Main Event "email perfomers" (which is a spin off of "mail to role") - 
- all Regular Act competition performers get emails (13ppl)
- Non-compete (14 ppl) - 
   - Mistress Manifest, Moxie Blue - has email turned off
   - Rouge Storm is Stormy Devine, Vix Versa is Nicolette Roux, 
   - So 12 of them are actually getting mail
- that's the 25 people

You (Scratch) are not cast at the Main Event MC yet - you have two act bids in - 1 is attached to the Bordello and 1 isn't attached to anything.

So... I can't find a bug here.  The logic is a lot, and annoying but it's working as designed. 

Quick logic summary:

- Mail to roles mails to ALL people in a role of (whatever role) - including all troupe members.
- It excludes anyone who turned off "Email me based on my past and current activities"
- It shows the Display Names of the email recipients.  So if Lili VonSchtup makes a performer called The Great Boobdini, it will show Lili as getting the mail, not Boobdini.
