### ISSUE TITLE
Does "Waitlisted" = Performer Role?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#588]
I just got email from someone on the waitlist asking about the status of their act.  Now, I know Expo email often ends up in people's spam, but I want to make sure that if something is sent to "Performers" it goes to people on the waitlist too.  If not, it probably should...

**Comment by bethlakshmi** [comment]
It does not.  A bid is waitlisted, but not attached to any show.  The show is on the form, but it's not a thing that we save, it's not a role in an event.  So - TLDR - they aren't performers.

**Comment by bethlakshmi** [comment]
And changing this isn't trivial...
