### ISSUE TITLE
Upgrade to Python 3.X

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#63]
Python 2.7 support ended with Jan 1, 2020.
Subsquently, the libraries we use in our code are starting to pull their support.
This causes deployment issues as we can't/don't hard code every library version that our dependancies depend on - it's not a matter of the libraries that WE chose changing (we do fix on those versions) - but the libraries underneath those libraries - stuff I've never heard of.

Every time we have a library upgrade that no longer includes Python 2.7, I have a failure in the deployment on Divio, which I then have to go back, research and workaround by fixing on a python 2.7 compatible version.  In fact, I'm doing that right now, and it's the 3rd time in the last 2 weeks.

I am hanging on by tooth and nail, but I will address this as CRITICAL in April, if not before.

**Comment by burlexpo** [comment]
Is this something we can ask Divio about addressing?

**Comment by bethlakshmi** [comment]
Not really.  This isn't their fault.

And they've been warning me for about 3 months that I'd have a hard time supporting Python 2.7 once it went out of support on Jan 1. 

This isn't their fault - the way python dependancies are declared, most libraries say "get version >= X", so the installer does so, typically getting the latest version.  Now... the latest version is not compliant with our needs, because it dropped Python 2.7 support.  Divio doesn't know all our dependancies and won't reach into our files to set them - that's my job.
