### ISSUE TITLE
Volunteer Bid removal remaining bits

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#72]
We (probably forever) want to keep the details about:
- people who volunteered at the expo in the Past
- what they said in their Bid
- their interests

But I think we could remove and thus simplify a bunch of code around:
- Available windows - these were always weird, if we did them again, I'd want to set up something different.  And with the changes in #19, we don't need to use them this year.  So they are all the past... can I remove data and all references to it???

- Edit of volunteer bids - I think we want to keep review forever, but edit is it's own pile of code... we should review after April 19 2020 and see if it's worth keeping.

- connection between Interests and events - this was a way to help volunteer bids get matched to useful events.  I see that there may be other uses, but right now it's MOSTLY gone from the visible code.  If we can't think of a good use for the connection between interests and scheduled events, I recommend removing that, and leaving interests purely as a thing connected to volunteer bids from the old way.

**Comment by burlexpo** [comment]
Kill “Available Windows”. I’m fine with revisiting the rest after the Expo

**Comment by bethlakshmi** [comment]
Closed under separate ticket.  Removal is done.
