### ISSUE TITLE
Bulk Email - please give exclued

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#78]
To keep this sane, I would keep each search as the type it is (roles or biddlers) - please let's not cross wire it, or the search will never be right (or complete).

But we want a way to say "get me all performers in GBE 2020, unless they are also teachers" - will need to work with @burlexpo to see how the semantics work.  For example, a search on all performers but not teachers in 2020 suggests that if they were performers OR teachers in 2018, it is completely irrelevant.  And a search on all performers AND all teachers in 2020 but not in 2018, suggests that if they were volunteers in 2018, that fact is irrelevant both for inclusion AND exclusion?

**Comment by bethlakshmi** [comment]
Hmm.... I just hit a conundrum in the UI.

I'm working on the bidder email as the first step....

- When I built the filter as it is, I decided NOT to infer that no-checkmarks = include everything.  My reason was mostly that it got really messy in my business logic.  Instead, it was pretty easy to bug the user and say "hey, give me SOMETHING".  That's a bit different than the typical inference, that zero choices = don't exclude anything, ie, include everything related to this parameter.
- now when I hit the "exclude" - I'm even more confused:
    - when a user leaves the whole "exclude" section blank, then they obviously mean "don't exclude anything"....  it would be crazy to MAKE them pick something to exclude.
    - what happens if they fill in some things, but not others?  The inference would normally be, "leave any unmade selections as "include all", except we're talking about "include any of these values as part of the exclusion".  Except that breaks the mould for what I did in the inclusions.

The whole thing is making my head hurt.

Right now, my default approach is going to be "make the system consistent for both exclude and include" - ie, make the user choose SOMETHING for everything if they want to use the feature.  In other words:

       - if they want to use the filter at, they have to give a value for conference, bid type and state - if they want everything, they should check everything.
       - if they want to avoid any exclusions, they can leave the whole set blank.  But as soon as they fill any field, they need to include at least one of EVERY field.

At least then it's consistent??

**Comment by burlexpo** [comment]
My take on the current process is

1) I check off the selection criteria I want included
2) The computer gathers up everyone who fulfills any of my criteria
3) The computer checks for and eliminates duplicates, because people are likely to appear in more than one category
4) The computer renders a list, complete with checkboxes so I can remove individuals for my own reasons.

My take on the *new* process is

1) I check off the selection criteria I want included
2) I check off the selection criteria I want excluded 
3) The computer gathers up everyone who fulfills any of my selection criteria into List I
4) The computer gathers up everyone who fulfills any of my selection criteria into List E
5) The computer checks for and eliminates duplicates on each list, giving me List ID and List ED
6) The computer removes all of the email addresses on List ED from List ID, rendering List M complete with checkboxes so I can remove individuals for my own reasons.

**Comment by bethlakshmi** [comment]
That much is true.
But that doesn't answer my question.

Writing in your terms:

On step #1 - you check off selection criteria.
- you want every conference
- the folks who proposed acts
- Including both waitlisted and accepted

On step #2, you want to EXCLUDE the folks who also proposed classes AND were accepted

....  my question:
- to do that - did you check off every conference?  
   - for step 1?
   - and for step 2?

You didn't want to limit by a conference.... so I could see how you might not want to check off ANY conference.

But... in my form (both what's live and what I'm building) - no checked options is basically invalid.

**Comment by burlexpo** [comment]
I'm confused as to where your confusion is.  This is what I see the interface looking like
![Exclusion Example](https://user-images.githubusercontent.com/5369404/74251847-befb7500-4cba-11ea-8e0f-2a99d63fa714.jpg)

I create the list of people I want
I create the list of people I don't want
I remove the second list from the first

If I don't select anyone to be removed, then no one is removed.

**Comment by bethlakshmi** [comment]
First off, please check this link:

https://burlesque-expo-stage.us.aldryn.io/email/mail_to_bidders

I see you cutting and pasting, and I've already written the GUI code.  That's not what I'm asking.

---------

Next, I'm trying to ask, what should happen when you have EXACTLY these selections:

![Screen Shot 2020-02-12 at 12 14 48 AM](https://user-images.githubusercontent.com/4542707/74305086-e428cb80-4d2c-11ea-898b-49c9c4a2e292.png)

Notice where the big red circle is - no conference has been selected.  

Should it be:

A - an error - because you have not given the form all three choices - conference, bid type, and state.  And to give NO conference means to basically make a query that has no entries.
B - create an EXCLUSION LIST of anyone who has ever had a class that was accepted, in ANY conference, - because that's what "no choices for conference" means.  And then look for the list of all costume submitters (except the summer GBE) that have been accepted and are not on the exclusion list.

Please look at and play with the form on the link here a bit before you answer.

**Comment by bethlakshmi** [comment]
Live on GBE!
