### ISSUE TITLE
Display order for tickets

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#89]
The items on http://burlesque-expo.com/ticketing/ don't seem to be displayed in any useful order.  They're not chronological by date/time they occur, they're not alphabetical, and they're not in any price order.

Can we sort them in descending order from highest price to lowest? In the case of multiple prices, use the highest available for an individual item

**Comment by burlexpo** [comment]
I thought this had been done.  Should this be closed? If not, I'm bumping up the priority level to MEDIUM

**Comment by bethlakshmi** [comment]
It looks no - it wasn't done.  Right now they are ordered by conference, in case there are two conferences running.

Should be doable.

**Comment by bethlakshmi** [comment]
#184
