### ISSUE TITLE
Vendor business addresses don't appear

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/gbe-divio-djangocms-python2.7#9]
This isn't new, the bug exists in the webfactional code

**Comment by burlexpo** [comment]
Most vendors don’t actually want their address to appear, so I think this is pretty low priority.  

--
Team BurlExo
Burlesque-Expo.com
#BurlExpo

**Comment by bethlakshmi** [comment]
This is actually that they don't appear on the review page that our vendor reviewer/approver sees.

**Comment by bethlakshmi** [comment]
Will be fixed in #76 - found issue during regressive testing.
