### ISSUE TITLE
Make it possible to sign up for a rehearsal slot on it's own

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#90]
Currrently, you have to fill out your complete tech form in order to sign up for a rehearsal slot.  Can we break things out so people can just sign up for a slot and fill out tech info later?

**Comment by bethlakshmi** [comment]
Duplicate of #91 at this point.

**Comment by bethlakshmi** [comment]
Fixed by #91
